-- GENERATED by tools/slice_hud_sheets.js — DO NOT EDIT BY HAND.
--
-- Advance widths for the custom HUD typeface, MEASURED from the delivered
-- sheets' own alpha channels. Hand-authoring these would create a second
-- source of truth that nothing regenerates; deriving them means a redrawn
-- glyph re-spaces itself on the next slice and the art cannot drift from its
-- metrics. Same doctrine as the generated _tod_door_data.gsc.
--
--   cw/ch     the cell each glyph was cut from
--   baseline  y of the baseline WITHIN that cell
--   cap       cap height in cell pixels
--   g[c].adv  ink width in SOURCE pixels; g[c].x its left edge
--
-- KEYED BY SET because both sheets carry a "-" and they are different
-- glyphs: digits["-"] is the wide marker a weapon with no magazine shows in
-- place of an ammo count, letters["-"] is the in-word hyphen in "AK-47".

CoD.TodGlyphMetrics = {
	digits = {
		cw = 128, ch = 160, baseline = 152, cap = 137,
		g = {
			["0"] = { adv = 113, x = 8, w = 113 },
			["1"] = { adv = 80, x = 24, w = 80 },
			["2"] = { adv = 113, x = 8, w = 113 },
			["3"] = { adv = 113, x = 8, w = 113 },
			["4"] = { adv = 113, x = 8, w = 113 },
			["5"] = { adv = 113, x = 8, w = 113 },
			["6"] = { adv = 113, x = 8, w = 113 },
			["7"] = { adv = 113, x = 8, w = 113 },
			["8"] = { adv = 113, x = 8, w = 113 },
			["9"] = { adv = 113, x = 8, w = 113 },
			["/"] = { adv = 80, x = 24, w = 80 },
			["+"] = { adv = 94, x = 17, w = 94 },
			["-"] = { adv = 95, x = 17, w = 95 },
		},
	},
	letters = {
		cw = 80, ch = 112, baseline = 103, cap = 89,
		g = {
			["a"] = { adv = 72, x = 4, w = 72 },
			["b"] = { adv = 66, x = 7, w = 66 },
			["c"] = { adv = 66, x = 7, w = 66 },
			["d"] = { adv = 66, x = 7, w = 66 },
			["e"] = { adv = 62, x = 9, w = 62 },
			["f"] = { adv = 60, x = 10, w = 60 },
			["g"] = { adv = 68, x = 6, w = 68 },
			["h"] = { adv = 66, x = 7, w = 66 },
			["i"] = { adv = 46, x = 17, w = 46 },
			["j"] = { adv = 58, x = 11, w = 58 },
			["k"] = { adv = 68, x = 6, w = 68 },
			["l"] = { adv = 60, x = 10, w = 60 },
			["m"] = { adv = 76, x = 2, w = 76 },
			["n"] = { adv = 68, x = 6, w = 68 },
			["o"] = { adv = 68, x = 6, w = 68 },
			["p"] = { adv = 64, x = 8, w = 64 },
			["q"] = { adv = 75, x = 3, w = 75 },
			["r"] = { adv = 68, x = 6, w = 68 },
			["s"] = { adv = 64, x = 8, w = 64 },
			["t"] = { adv = 64, x = 8, w = 64 },
			["u"] = { adv = 66, x = 7, w = 66 },
			["v"] = { adv = 72, x = 4, w = 72 },
			["w"] = { adv = 76, x = 2, w = 76 },
			["x"] = { adv = 70, x = 5, w = 70 },
			["y"] = { adv = 70, x = 5, w = 70 },
			["z"] = { adv = 64, x = 8, w = 64 },
			["-"] = { adv = 50, x = 15, w = 50 },
			["'"] = { adv = 30, x = 25, w = 30 },
			["$"] = { adv = 74, x = 4, w = 74 },
			["."] = { adv = 34, x = 23, w = 34 },
		},
	},
}
