-- =============================================================================
-- TodGlyphRow — THE CUSTOM TYPEFACE, as a shared row factory.
--
-- LIFTED VERBATIM OUT OF AetheriumLoadout.lua (v17.25). Nothing in the layout
-- maths below changed; the file exists because a SECOND widget now sets text in
-- the baked typeface — the top-right ROUND readout, which replaced the stock
-- ZmRndContainer (user 2026-09-04: "We have the round image in the top right of
-- screen but I am looking to replace with the alphabet and letters we have
-- downloaded ... Lets remove stock and track ourselves").
--
-- ONE COPY, DELIBERATELY. The alternative was to paste the ~120 lines into the
-- round counter, and this map has a standing rule about exactly that: a second
-- copy of a number is a second source of truth that nothing regenerates. It is
-- worse here than usual, because the layout maths is the CONSUMER of the
-- GENERATED metrics in TodGlyphMetrics.lua — a re-slice would silently fix one
-- copy and not the other, and the failure mode is text that overlaps by two
-- pixels, which nobody files a bug about.
--
-- WHAT A CALLER GETS:
--   CoD.TodGlyphRow.make( owner, n )   a pooled row of n UIImages, with
--                                      .set / .measure / .hide / .setRGB
--   CoD.TodGlyphRow.digitSet           set picker: digits only (numbers)
--   CoD.TodGlyphRow.nameSet            set picker: letters, and the digit
--                                      sheet for 0-9 + / ("AK-47", "+30", "HP/S")
--   CoD.TodGlyphRow.imageCount( str )  images a string needs (% = 3, : = 2)
--   row.grow( m )                      add images up to m (never shrinks)
-- "%" and ":" are composites of existing cells (v19.58); see TOD_COMPOSITE.
-- The two image mappers are exported too, but only the pickers are normally
-- needed: .set resolves the image itself.
--
-- THE POOL IS THE POINT. Elements are created ONCE at construction and only
-- their image and rect are written per update. Creating and closing elements on
-- every tick is a documented state-pool leak in this tree.
-- =============================================================================

require( "ui.uieditor.widgets.HUD.AetheriumWidgets.TodGlyphMetrics" )  -- GENERATED by tools/slice_hud_sheets.js

-- =============================================================================
-- THE CUSTOM TYPEFACE
--
-- User 2026-09-03: "I wonder if we should get creative with digits and letters
-- as well so we can have custom text and numbers as well. That would be sick."
-- So every number and the weapon name in the gun HUD, and the ROUND readout in
-- the top-right corner, are assembled from baked glyph art. There is no system
-- font left in either corner.
--
-- HOW IT WORKS. Each glyph is one UIImage from a POOL created once at
-- construction — never per update. Creating and closing elements on every ammo
-- tick is what two weapon-swap UITimers in AetheriumLoadout used to do, and they
-- were a documented state-pool leak. Setting an image and a rect on a pooled
-- element allocates nothing.
--
-- METRICS ARE DERIVED, NOT TYPED. CoD.TodGlyphMetrics is GENERATED by
-- tools/slice_hud_sheets.js, which measures every cell's ink from its own alpha
-- channel. It carries, per set: the cell size, the baseline's y WITHIN the cell,
-- the cap height, and each glyph's ink width and left edge. Redraw a glyph
-- narrower and the spacing follows on the next slice — the art and its metrics
-- cannot drift.
--
-- WHY THE SETS ARE SEPARATE. A weapon name mixes both sheets ("AK-47",
-- "MP117 REDACTOR"), and they were drawn on different cells — digits 128x160
-- with a 137 cap, letters 80x112 with an 89 cap. Sitting them on one line means
-- scaling each set so its CAP HEIGHT matches, then aligning each set's own
-- BASELINE. Both numbers come out of the table, so neither is hardcoded here.
-- The two sets also both carry a "-", and they are different glyphs: the digit
-- one is the wide marker a blade shows in place of an ammo count, the letter one
-- is the hyphen inside "AK-47".
-- =============================================================================

-- A space has no glyph, only an advance. Expressed as a fraction of the cell so
-- it scales with everything else.
local TOD_SPACE_ADV  = 0.30
local TOD_TRACK      = 0.055   -- letter spacing, as a fraction of cap height

local function todDigitImage( c )
	if c >= "0" and c <= "9" then return "i_tod_hud_d" .. c end
	if c == "/" then return "i_tod_hud_dslash" end
	if c == "+" then return "i_tod_hud_dplus" end
	if c == "-" then return "i_tod_hud_ddash" end
	return nil
end

local TOD_LETTER_IMG = {
	[ "-" ] = "i_tod_hud_lhyphen",
	[ "'" ] = "i_tod_hud_lapos",
	[ "." ] = "i_tod_hud_ldot",
	-- v19.2: the map's own points icon, in the cell the dead ampersand used to
	-- hold. "$" therefore draws the SAME money symbol the player HUD shows, in
	-- every readout that uses this typeface -- no second currency mark exists.
	[ "$" ] = "i_tod_hud_lmoney",
}
local function todLetterImage( c )
	if c >= "A" and c <= "Z" then return "i_tod_hud_l" .. string.lower( c ) end
	return TOD_LETTER_IMG[ c ]
end

-- Which set a character belongs to, for a NAME (which may mix them).
-- v19.58 (2026-09-27, the map-wide typography pass): "+" and "/" live on the
-- DIGIT sheet, and a name string now routes them there instead of failing the
-- whole measure - "+30", "HP/S", "1/3" read in running text. Everything else
-- still rides the letter sheet.
local function todNameSet( c )
	if ( c >= "0" and c <= "9" ) or c == "+" or c == "/" then return "digits" end
	return "letters"
end

-- COMPOSITE MARKS (v19.58). The typeface has no "%" or ":" cell, and the pause
-- menu / scoreboard copy is full of both ("+30% DAMAGE", "BACK IN 4:00").
-- Rather than bake new art, each is ASSEMBLED from cells that exist, so it
-- carries the same bevel and colour as every glyph around it:
--   %  a small 0 at the cap top, the digit "/", a small 0 on the baseline
--   :  two letter-sheet "." stacked
-- Each part is { set, key, scale (of cap), dx (of the small-glyph advance), dy
-- (of cap, negative = up) }. The advance is computed from the parts.
local TOD_PCT_SMALL = 0.42
local TOD_COMPOSITE = {
	[ "%" ] = true,
	[ ":" ] = true,
}

-- ONE GLYPH'S DRAW PARTS. Returns adv, parts (each { img, left, top, w, h }
-- relative to pen / baseline), or nil when the glyph does not exist.
local function todGlyphParts( M, c, cap, setPicker )
	local function one( setName, key, k, x0, dy )
		local S = M[ setName ]
		local gm = S and S.g[ ( setName == "letters" ) and string.lower( key ) or key ]
		if not gm then return nil end
		local s = ( cap * k ) / S.cap
		local img = ( setName == "digits" ) and todDigitImage( key ) or todLetterImage( key )
		if not img then return nil end
		return {
			img = img,
			left = x0 - gm.x * s,
			top = dy - S.baseline * s,
			w = S.cw * s,
			h = S.ch * s,
			adv = gm.adv * s,
		}
	end

	if TOD_COMPOSITE[ c ] then
		if c == "%" then
			local z = one( "digits", "0", TOD_PCT_SMALL, 0, 0 )
			local sl = one( "digits", "/", 1, 0, 0 )
			if not z or not sl then return nil end
			local zw = z.adv
			local top0 = one( "digits", "0", TOD_PCT_SMALL, 0, -cap * ( 1 - TOD_PCT_SMALL ) )
			local slash = one( "digits", "/", 1, zw * 0.35, 0 )
			local bot0 = one( "digits", "0", TOD_PCT_SMALL, zw * 0.35 + sl.adv - zw * 0.65, 0 )
			return sl.adv + zw * 0.7, { top0, slash, bot0 }
		end
		-- ":"
		local lo = one( "letters", ".", 1, 0, 0 )
		local hi = one( "letters", ".", 1, 0, -cap * 0.52 )
		if not lo or not hi then return nil end
		return lo.adv, { lo, hi }
	end

	local setName = setPicker( c )
	local p = one( setName, c, 1, 0, 0 )
	if not p then return nil end
	return p.adv, { p }
end

-- How many images a string needs (a composite takes more than one). Callers
-- that size a pool from a string use this, never #str.
local function todImageCount( str )
	local n = 0
	for i = 1, #str do
		local c = string.sub( str, i, i )
		if c == "%" then n = n + 3
		elseif c == ":" then n = n + 2
		elseif c ~= " " then n = n + 1 end
	end
	return n
end

-- A POOLED ROW OF GLYPHS. `owner` is the element to add into; `n` the pool size.
local function todMakeGlyphRow( owner, n )
	local row = { img = {}, n = n }
	local function addImages( m )
		for i = row.n_built + 1, m do
			local e = LUI.UIImage.new()
			e:setLeftRight( true, false, 0, 1 )
			e:setTopBottom( true, false, 0, 1 )
			e:setImage( RegisterImage( "blacktransparent" ) )
			e:setRGB( row.r or 1, row.g or 1, row.b or 1 )
			e:setAlpha( 0 )
			owner:addElement( e )
			row.img[ i ] = e
		end
		if m > row.n_built then row.n_built = m end
		row.n = row.n_built
	end
	row.n_built = 0
	addImages( n )

	-- GROW, never shrink (v19.58): a label whose text gets longer adds the
	-- missing images once; the pool then stays at its high-water mark.
	row.grow = function ( m )
		if m > row.n_built then addImages( m ) end
	end

	row.hide = function ()
		for i = 1, row.n do row.img[ i ]:setAlpha( 0 ) end
	end

	row.close = function ()
		for i = 1, row.n do row.img[ i ]:close() end
	end

	row.setRGB = function ( r, g, b )
		row.r, row.g, row.b = r, g, b
		for i = 1, row.n do row.img[ i ]:setRGB( r, g, b ) end
	end

	-- Width of `str` at `cap`, or -1 if any glyph is missing (the caller then
	-- falls back rather than drawing a gap).
	row.measure = function ( str, cap, setPicker )
		local M = CoD.TodGlyphMetrics
		if not M then return -1 end
		local w, first = 0, true
		for i = 1, #str do
			local c = string.sub( str, i, i )
			if c == " " then
				local S = M.letters
				w = w + S.cw * ( cap / S.cap ) * TOD_SPACE_ADV
			else
				local adv = todGlyphParts( M, c, cap, setPicker )
				if not adv then return -1 end
				if not first then w = w + cap * TOD_TRACK end
				w = w + adv
			end
			first = false
		end
		return w
	end

	-- Lay `str` out so its right edge lands on rightX and every glyph sits on
	-- baselineY. Returns the width, or -1 (row hidden) if a glyph is missing.
	row.set = function ( str, cap, rightX, baselineY, setPicker )
		local M = CoD.TodGlyphMetrics
		row.hide()
		if not M or str == nil or str == "" then return 0 end
		local total = row.measure( str, cap, setPicker )
		if total < 0 then return -1 end
		local pen, used, first = rightX - total, 0, true
		for i = 1, #str do
			local c = string.sub( str, i, i )
			if c == " " then
				local S = M.letters
				pen = pen + S.cw * ( cap / S.cap ) * TOD_SPACE_ADV
			else
				local adv, parts = todGlyphParts( M, c, cap, setPicker )
				if adv then
					if not first then pen = pen + cap * TOD_TRACK end
					if used + #parts > row.n then break end
					for j = 1, #parts do
						local p = parts[ j ]
						used = used + 1
						local e = row.img[ used ]
						local left = pen + p.left
						local top  = baselineY + p.top
						e:setImage( RegisterImage( p.img ) )
						e:setLeftRight( true, false, left, left + p.w )
						e:setTopBottom( true, false, top, top + p.h )
						e:setAlpha( 1 )
					end
					pen = pen + adv
				end
			end
			first = false
		end
		return total
	end

	return row
end

-- Numbers use the digit set only; names may mix.
local function todSetDigits() return "digits" end

-- The export. Locals above stay local so nothing can reach past this table.
CoD.TodGlyphRow = {
	make        = todMakeGlyphRow,
	digitSet    = todSetDigits,
	nameSet     = todNameSet,
	imageCount  = todImageCount,
	digitImage  = todDigitImage,
	letterImage = todLetterImage,
}
