// GENERATED by tools/gen_tower_map.js — DO NOT HAND-EDIT (regen instead).
// THE ENDLESS SPIRE anchors (docs/44): door positions ride the same
// arithmetic that cut the slabs, so script and geometry cannot drift.
// Doors have NO map triggers — _tod_spire spawns them lazily in the climb
// window (the gentity-table budget, docs/44 §4).

#namespace tod_spire_data;

function spire_x()        { return 10240; }
function spire_y()        { return 0; }
function spire_laps()     { return 100; }
function spire_top()      { return 38400; }
function spire_summit_z() { return 38592; }
function door_cost()      { return 3000; }
function summit_cost()    { return 7500; }

// Is this point anywhere on the spire (arena, spiral, hubs, summit)?
function in_spire( org )
{
	return ( org[ 0 ] > 8840 && org[ 0 ] < 11640 && org[ 1 ] > -1400 && org[ 1 ] < 1400 );
}

// Door n gates floor n at z=(n-1)*384. Same shape as tod_door_data.
function get_spire_door_info( n )
{
	b = ( n - 1 ) * 384;
	info = SpawnStruct();
	if ( ( n % 2 ) == 1 )
		info.org = ( 10576, -256, b + 40 );
	else
		info.org = ( 9904, 256, b + 40 );
	info.off = ( 0, 60, 0 );
	info.cost = 3000;
	info.flag = "enter_spire" + n;
	info.target = "tod_spire_door" + n;
	info.dest = "the Spire - Floor " + n;
	return info;
}
function spire_door_z( n ) { return ( n - 1 ) * 384; }

// Crate shelf per floor (floors 5+; hub floors use the hub crate; the
// arena crate covers 1-4). undefined = no shelf on that floor.
function shelf_crate_org( n )
{
	if ( n < 5 || ( n % 10 ) == 0 )
		return undefined;
	mid = ( n - 1 ) * 384 + 192;
	if ( ( n % 2 ) == 1 )
		return ( 10766, 336, mid );
	return ( 9714, -336, mid );
}
function shelf_crate_yaw( n ) { return ( ( ( n % 2 ) == 1 ) ? 270 : 90 ); }
function arena_crate_org() { return ( 10040, -505, 0 ); }
function arena_crate_yaw() { return 359.999; }

// vendor hubs (every 10th floor, mirrored/even frame — BR_FURN anchors)
function hub_laps() { return array( 10, 20, 30, 40, 50, 60, 70, 80, 90, 100 ); }
function hub_z( lap ) { return ( lap - 1 ) * 384 + 192; }
function hub_pap_org( z )  { return ( 9496, -680, z ); }
function hub_pap_trig( z ) { return ( 9552, -680, z ); }
function hub_pap_yaw()     { return 90; }
function hub_crate_org( z ){ return ( 9930, -700, z ); }
function hub_crate_yaw()   { return 270; }
function hub_perk_pads( z )
{
	a = [];
	a[ 0 ] = ( 9880, -970, z );
	a[ 1 ] = ( 9704, -970, z );
	return a;
}

// arrival + arena perk pads + summit
function arrival_org()     { return ( 10040, 0, 0 ); }
function arena_perk_pads()
{
	a = [];
	a[ 0 ] = ( 10110, 511, 0 );
	a[ 1 ] = ( 10370, 511, 0 );
	return a;
}
function summit_exfil_org(){ return ( 10240, -150, 38616 ); }
function beacon_org()      { return ( 10240, 0, 39128 ); }

// THE ASCENSION PAD — on the crown hall DAIS (the focal point the uplink
// left behind in v10). Crown-frame coordinates, pre-mirrored like every
// _tod_crown_data anchor.
function ascension_pad_org() { return ( 0, 8608, 19408 ); }
function ascension_pad_yaw() { return 180; }

// zone bookkeeping for the wiring (zonemgr adjacency, spawn filter)
function zone_chunk() { return 5; }
function spire_zone_of( n ) { return "spire_c" + ( int( ( n - 1 ) / 5 ) + 1 ) + "_zone"; }
function spire_zone_names()
{
	a = [];
	a[ 0 ] = "spire_base_zone";
	a[ 1 ] = "spire_c1_zone";
	a[ 2 ] = "spire_c2_zone";
	a[ 3 ] = "spire_c3_zone";
	a[ 4 ] = "spire_c4_zone";
	a[ 5 ] = "spire_c5_zone";
	a[ 6 ] = "spire_c6_zone";
	a[ 7 ] = "spire_c7_zone";
	a[ 8 ] = "spire_c8_zone";
	a[ 9 ] = "spire_c9_zone";
	a[ 10 ] = "spire_c10_zone";
	a[ 11 ] = "spire_c11_zone";
	a[ 12 ] = "spire_c12_zone";
	a[ 13 ] = "spire_c13_zone";
	a[ 14 ] = "spire_c14_zone";
	a[ 15 ] = "spire_c15_zone";
	a[ 16 ] = "spire_c16_zone";
	a[ 17 ] = "spire_c17_zone";
	a[ 18 ] = "spire_c18_zone";
	a[ 19 ] = "spire_c19_zone";
	a[ 20 ] = "spire_c20_zone";
	a[ 21 ] = "spire_summit_zone";
	return a;
}
