#!/usr/bin/env python3
"""THE LEVEL PIPS ON EVERY UPGRADE CARD (docs/172, user 2026-10-04).

User: "players arent really aware of what basic, super, and ultimate even mean and
will pick up a basic instead of ultimate ... a visual upgrade on all the cards that
has to be custom and not part of the actual card but should look like it ... shows
all the levels of that upgrade, fills in the level you are and then shows what the
upgrade will take you ... Fill Fill Purple Purple Empty ... maybe even a small pulse
animation on the purple dots ... I dont think this impacts dark upgrades at all."

The row is LIVE: tod_upgrade.lua draws one pip per level of the domain (the player's
real per-class max), the levels already owned in the pause menu's own cyan, the levels
THIS card adds in the card's rarity colour (pulsing), the rest empty. This tool owns
everything that is an IMAGE in that feature:

  1. THE SPRITES - ten small PNGs rebuilt from the card art's own dot (core, black
     outline, rarity halo, the highlight spot), fitted to the baked dots: mean error
     under one colour step of 255 (validate()). 48 texels = 48 card px, so a sprite
     carries exactly the card art's texel density and filters the way the card does.
  2. THE CARDS - every zoned regular / super / ultimate card and the ten class-tier
     cards carried a BAKED dot row (the rarity's +N, never the player's level). Those
     dots are painted out with the card's own flat panel colour, inside a measured
     band, after proving the band held nothing but dots. A cover sprite cannot do it:
     an unfocused card is drawn at alpha 0.4, and a cover composited over a
     translucent card shows the baked dots through it and reads as a patch. DARK cards
     keep their baked dots (a dark card is dealt on a maxed domain; the live row skips
     it - the user's call). The originals are parked in tmp/card_pips/originals.
  3. THE WIRING - the image.gdf blocks (source_data/tod_ui_images.gdt) and a GENERATED
     `image,` block in the zone, both written here and checked here.

  python tools/card_pips/build_card_pips.py --install    sprites + GDT + zone + paint out dots
  python tools/card_pips/build_card_pips.py --check      verify, write nothing (BUILD GATE)
  python tools/card_pips/build_card_pips.py --preview D  mock cards with live rows -> D/*.png
  python tools/card_pips/build_card_pips.py --restore    put every parked original back

A NEW CARD DROP ARRIVES WITH BAKED DOTS. --check fails on it by name; --install paints
them out. Never hand-edit the generated zone block or the GDT blocks.

LOCKSTEP with tod_upgrade.lua (`PIP_*` constants): the dot centre (384, 1028), the
baked pitch 58, the usable width 428, the halo radius 22.1 and the 48 / 80 texel
footprints. --check reads them out of the Lua and fails on drift.
"""
import argparse
import hashlib
import json
import os
import re
import shutil
import sys

import numpy as np
from PIL import Image

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
IMG_DIR = os.path.join(ROOT, 'source_data', 'tod_ui_images', '_images')
GDT = os.path.join(ROOT, 'source_data', 'tod_ui_images.gdt')
ZONE = os.path.join(ROOT, 'zone_source', 'zm_tower_of_doom.zone')
LUA = os.path.join(ROOT, 'ui', 'uieditor', 'menus', 'hud', 'tod_upgrade.lua')
PARK = os.path.join(ROOT, 'tmp', 'card_pips', 'originals')
MANIFEST = os.path.join(ROOT, 'tmp', 'card_pips', 'manifest.json')

ZBEGIN = '// BEGIN card_pips (GENERATED by tools/card_pips/build_card_pips.py - do not edit)'
ZEND = '// END card_pips'
ZANCHOR = 'image,i_tod_pause_pip_empty'

# ---- the card's dot, measured on the 768 x 1152 sources (validate() proves it) ----
CARD_W, CARD_H = 768, 1152
PIP_CX, PIP_CY = 384.0, 1028.0     # every baked row is centred here
PIP_PITCH = 58                     # baked centre-to-centre
PIP_USABLE_W = 428                 # x 170..598: between the panel's lower screws
R_CORE, R_OUT, R_HALO = 11.5, 16.5, 22.1
HL_OFF, HL_R0, HL_R1 = -3.0, 4.0, 5.0      # the highlight spot: centre offset, feather
OUTLINE = (4, 6, 14)
EMPTY_IN = (10, 16, 38)
SPRITE = 48                        # texels = card px (1:1 with the card art)
GLOW = 80
SS = 16                            # supersampling per axis

# core, highlight, halo (opaque, as the card art draws it; None = no halo)
BODIES = {
    'i_tod_cardpip_owned':         ((51, 217, 255), (245, 253, 255), None),        # the pause menu's own level pip colour
    'i_tod_cardpip_gain_regular':  ((234, 240, 246), (253, 254, 254), (119, 132, 164)),
    'i_tod_cardpip_gain_super':    ((212, 149, 255), (251, 246, 255), (113, 93, 161)),
    'i_tod_cardpip_gain_ultimate': ((255, 217, 84), (255, 251, 242), (135, 121, 98)),
    'i_tod_cardpip_gain_tier':     ((240, 245, 255), (254, 254, 255), (135, 119, 101)),
}
GLOWS = {
    'i_tod_cardpip_glow_regular':  (205, 228, 255),
    'i_tod_cardpip_glow_super':    (196, 120, 255),
    'i_tod_cardpip_glow_ultimate': (255, 200, 70),
}
SPRITES = ['i_tod_cardpip_empty'] + list(BODIES) + list(GLOWS) + ['i_tod_cardpip_shine']

# the band the baked dots live in (x 160..607, y 992..1060). Clear of the description
# box's lower edge (y 985..988), the panel's lower bevel (y 1063+) and both screws.
BAND = (160, 992, 608, 1061)       # x0, y0, x1 (excl), y1 (excl)


# ---------------------------------------------------------------------------------
# rendering
def _grid(n):
    g = (np.arange(n * SS) + 0.5) / SS
    return np.meshgrid(g, g)


def _disc(n, cx, cy, r):
    X, Y = _grid(n)
    return ((((X - cx) ** 2 + (Y - cy) ** 2) <= r * r).reshape(n, SS, n, SS)).mean(axis=(1, 3))


def _feather(n, cx, cy, r0, r1):
    X, Y = _grid(n)
    d = np.sqrt((X - cx) ** 2 + (Y - cy) ** 2)
    return np.clip((r1 - d) / (r1 - r0), 0, 1).reshape(n, SS, n, SS).mean(axis=(1, 3))


class Layers:
    """Straight-alpha 'over' compositing into a premultiplied buffer."""

    def __init__(self, n, bg=None):
        self.n = n
        self.rgb = np.zeros((n, n, 3))
        self.a = np.zeros((n, n))
        if bg is not None:
            self.rgb[:] = np.array(bg, float)
            self.a[:] = 1.0

    def over(self, col, cov, alpha=1.0):
        k = cov * alpha
        self.rgb = self.rgb * (1 - k[..., None]) + np.array(col, float)[None, None, :] * k[..., None]
        self.a = self.a * (1 - k) + k

    def rgba(self):
        out = np.zeros((self.n, self.n, 4))
        safe = np.where(self.a > 1e-6, self.a, 1)
        out[..., :3] = self.rgb / safe[..., None]
        out[..., 3] = self.a * 255.0
        return np.clip(np.round(out), 0, 255).astype(np.uint8)


def body_layers(kind, bg=None):
    n, c = SPRITE, SPRITE / 2.0
    L = Layers(n, bg)
    if kind == 'i_tod_cardpip_empty':
        L.over(OUTLINE, _disc(n, c, c, R_OUT))
        L.over(EMPTY_IN, _disc(n, c, c, R_CORE))
        return L
    core, hl, halo = BODIES[kind]
    if halo:
        L.over(halo, _disc(n, c, c, R_HALO))
    L.over(OUTLINE, _disc(n, c, c, R_OUT))
    L.over(core, _disc(n, c, c, R_CORE))
    L.over(hl, _feather(n, c + HL_OFF, c + HL_OFF, HL_R0, HL_R1))
    return L


def render_glow(col):
    # a soft light: full under the dot (hidden by it), then a falloff that is gone by
    # r ~34 card px. The Lua breathes its alpha and size.
    n, c = GLOW, GLOW / 2.0
    X, Y = _grid(n)
    d = np.sqrt((X - c) ** 2 + (Y - c) ** 2)
    a = np.where(d <= 16.0, 1.0, np.exp(-((d - 16.0) / 8.5) ** 2))
    a = a.reshape(n, SS, n, SS).mean(axis=(1, 3))
    out = np.zeros((n, n, 4), np.uint8)
    out[..., 0], out[..., 1], out[..., 2] = col
    out[..., 3] = np.clip(np.round(a * 230), 0, 255).astype(np.uint8)
    return out


def render_shine():
    # white over the core only, brightest at the centre: the dot itself lights up
    n, c = SPRITE, SPRITE / 2.0
    X, Y = _grid(n)
    d = np.sqrt((X - c) ** 2 + (Y - c) ** 2)
    edge = np.clip((R_CORE - d) / 1.0, 0, 1)
    a = edge * (1.0 - 0.35 * np.clip(d / R_CORE, 0, 1) ** 2)
    a = a.reshape(n, SS, n, SS).mean(axis=(1, 3))
    out = np.zeros((n, n, 4), np.uint8)
    out[..., :3] = 255
    out[..., 3] = np.clip(np.round(a * 255), 0, 255).astype(np.uint8)
    return out


def render(name):
    if name in GLOWS:
        return render_glow(GLOWS[name])
    if name == 'i_tod_cardpip_shine':
        return render_shine()
    return body_layers(name).rgba()


# ---------------------------------------------------------------------------------
# validation against the baked dots
VALIDATE = [
    # sprite (or a white-core twin for the regular lit dot), card, dot centre x
    ('i_tod_cardpip_empty', 'i_tod_card_headshot_regular.png', 442),
    ('i_tod_cardpip_gain_super', 'i_tod_card_headshot_super.png', 268),
    ('i_tod_cardpip_gain_ultimate', 'i_tod_card_headshot_ultimate.png', 268),
    ('i_tod_cardpip_gain_tier', 'i_tod_card_tier_assault_2.png', 326),
]


def validate(originals_dir):
    """Composite each sprite over the panel and diff it against the baked dot of the
    ORIGINAL card (the parked copy once the dots are painted out)."""
    rows, worst = [], 0.0
    for name, card, cx in VALIDATE:
        path = os.path.join(originals_dir, card)
        if not os.path.exists(path):
            path = os.path.join(IMG_DIR, card)
        a = np.array(Image.open(path).convert('RGB')).astype(float)
        x0, y0 = int(cx - SPRITE / 2), int(PIP_CY - SPRITE / 2)
        baked = a[y0:y0 + SPRITE, x0:x0 + SPRITE]
        if float(np.abs(baked - baked[0, 0]).max()) < 1:
            rows.append((name, None))      # the dots are gone from this copy
            continue
        panel = tuple(int(v) for v in a[1000, 200])
        ours = body_layers(name, bg=panel).rgb
        err = float(np.abs(ours - baked).mean())
        worst = max(worst, err)
        rows.append((name, err))
    return rows, worst


# ---------------------------------------------------------------------------------
# the cards
def zoned_cards():
    text = open(ZONE, encoding='utf-8').read()
    names = []
    for m in re.finditer(r'^image,(i_tod_card_[a-z0-9_]+)\s*$', text, re.M):
        n = m.group(1)
        if re.match(r'i_tod_card_tier_[a-z]+_[23]$', n) or re.match(r'i_tod_card_.+_(regular|super|ultimate)$', n):
            if n.startswith('i_tod_cardpip_'):
                continue
            names.append(n)
    return sorted(set(names))


def band_view(a):
    x0, y0, x1, y1 = BAND
    return a[y0:y1, x0:x1]


def panel_colour(a):
    band = band_view(a)[..., :3].reshape(-1, 3)
    vals, counts = np.unique(band, axis=0, return_counts=True)
    return tuple(int(v) for v in vals[counts.argmax()])


def band_clean(a):
    band = band_view(a)[..., :3]
    return bool((band == band[0, 0]).all())


def find_dots(a, panel):
    """Centres of the baked dots: a dot (lit or empty) never has a panel-coloured
    centre, and every baked row sits on the 29 px half-pitch grid about x 384."""
    found = []
    for s in range(-8, 9):
        cx = int(PIP_CX + s * (PIP_PITCH / 2.0))
        cy = int(PIP_CY)
        core = a[cy - 1:cy + 1, cx - 1:cx + 1, :3].astype(int)
        if (np.abs(core - panel).sum(axis=2) > 24).all():
            found.append(float(cx))
    return found


def paint_out(a):
    """Returns (new_array, n_dots) or raises ValueError when the band holds anything
    that is not one of the detected dots."""
    out = a.copy()
    x0, y0, x1, y1 = BAND
    panel = np.array(panel_colour(a))
    band = out[y0:y1, x0:x1]
    diff = np.abs(band[..., :3].astype(int) - panel).sum(axis=2) > 0
    if not diff.any():
        return out, 0
    dots = find_dots(a, panel)
    if not dots:
        raise ValueError('off-panel pixels in the dot band but no dot centre on the grid')
    for i in range(1, len(dots)):
        if dots[i] - dots[i - 1] < PIP_PITCH - 0.5:
            raise ValueError('dots closer than the baked pitch at x %.0f / %.0f' % (dots[i - 1], dots[i]))
    ys, xs = np.nonzero(diff)
    xs = xs + x0 + 0.5
    ys = ys + y0 + 0.5
    # every off-panel pixel must sit inside the footprint of a DETECTED dot
    r = np.min(np.stack([np.sqrt((xs - cx) ** 2 + (ys - PIP_CY) ** 2) for cx in dots]), axis=0)
    if (r > R_HALO + 1.5).any():
        bad = int((r > R_HALO + 1.5).sum())
        raise ValueError('%d off-panel pixel(s) in the dot band that belong to no dot' % bad)
    keep_alpha = band[..., 3].copy()
    band[diff, 0], band[diff, 1], band[diff, 2] = panel
    band[..., 3] = keep_alpha
    return out, len(dots)


def sha(path):
    return hashlib.sha256(open(path, 'rb').read()).hexdigest()


# ---------------------------------------------------------------------------------
# GDT + zone
def gdt_block(name):
    return ('\t"%s" ( "image.gdf" )\n\t{\n'
            '\t\t"arabicUnsafe" "0"\n'
            '\t\t"baseImage" "source_data/tod_ui_images/_images/%s.png"\n'
            '\t\t"clampU" "1"\n\t\t"clampV" "1"\n'
            '\t\t"colorSRGB" "1"\n'
            '\t\t"compressionMethod" "compressed high color"\n'
            '\t\t"coreSemantic" "sRGB3chAlpha"\n'
            '\t\t"doNotResize" "0"\n\t\t"forceStreaming" "0"\n\t\t"fromAlpha" "0"\n'
            '\t\t"imageType" "Texture"\n\t\t"mipBase" "1/1"\n\t\t"mipMode" "Average"\n'
            '\t\t"noMipMaps" "1"\n\t\t"noPicMip" "1"\n\t\t"premulAlpha" "0"\n'
            '\t\t"semantic" "diffuseMap"\n\t\t"streamable" "1"\n'
            '\t\t"textureAtlasColumnCount" "1"\n\t\t"textureAtlasRowCount" "1"\n'
            '\t\t"type" "image"\n\t}\n') % (name, name)


def gdt_has(text, name):
    return re.search(r'^\t"%s" \( "image\.gdf" \)' % re.escape(name), text, re.M) is not None


def zone_block(nl):
    return nl.join([ZBEGIN] + ['image,' + n for n in SPRITES] + [ZEND])


def zone_text():
    raw = open(ZONE, 'rb').read().decode('utf-8')
    nl = '\r\n' if '\r\n' in raw else '\n'
    return raw, nl


# ---------------------------------------------------------------------------------
# LOCKSTEP with the Lua
LUA_LOCKSTEP = {
    'PIP_CX': PIP_CX, 'PIP_CY': PIP_CY, 'PIP_PITCH': PIP_PITCH,
    'PIP_USABLE_W': PIP_USABLE_W, 'PIP_HALO_R': R_HALO,
    'PIP_SPRITE': SPRITE, 'PIP_GLOW': GLOW,
}


def lua_lockstep_errors():
    errs = []
    try:
        lua = open(LUA, encoding='utf-8').read()
    except OSError as e:
        return ['cannot read %s: %s' % (LUA, e)]
    for k, v in LUA_LOCKSTEP.items():
        m = re.search(r'\b%s\s*=\s*([0-9.]+)' % k, lua)
        if not m:
            errs.append('tod_upgrade.lua has no %s (LOCKSTEP with this tool: %s)' % (k, v))
        elif abs(float(m.group(1)) - float(v)) > 1e-6:
            errs.append('tod_upgrade.lua %s = %s, this tool says %s' % (k, m.group(1), v))
    for n in SPRITES:
        if ('"%s"' % n) not in lua:
            errs.append('tod_upgrade.lua never registers %s' % n)
    return errs


# ---------------------------------------------------------------------------------
def write_sprites():
    changed = []
    for n in SPRITES:
        arr = render(n)
        path = os.path.join(IMG_DIR, n + '.png')
        if os.path.exists(path):
            old = np.array(Image.open(path).convert('RGBA'))
            if old.shape == arr.shape and (old == arr).all():
                continue
        Image.fromarray(arr, 'RGBA').save(path, optimize=True)
        changed.append(n)
    return changed


def write_gdt():
    text = open(GDT, 'rb').read().decode('ascii')
    add = [n for n in SPRITES if not gdt_has(text, n)]
    if not add:
        return []
    end = text.rstrip().rfind('}')
    text = text[:end] + ''.join(gdt_block(n) for n in add) + text[end:]
    open(GDT, 'wb').write(text.encode('ascii'))
    return add


def write_zone():
    raw, nl = zone_text()
    block = zone_block(nl)
    if ZBEGIN in raw:
        s = raw.index(ZBEGIN)
        e = raw.index(ZEND, s) + len(ZEND)
        new = raw[:s] + block + raw[e:]
    else:
        i = raw.index(ZANCHOR)
        j = raw.index(nl, i) + len(nl)
        new = raw[:j] + block + nl + raw[j:]
    if new != raw:
        open(ZONE, 'wb').write(new.encode('utf-8'))
        return True
    return False


def load_manifest():
    if os.path.exists(MANIFEST):
        return json.load(open(MANIFEST, encoding='utf-8'))
    return {'cards': {}}


def save_manifest(m):
    os.makedirs(os.path.dirname(MANIFEST), exist_ok=True)
    json.dump(m, open(MANIFEST, 'w', encoding='utf-8'), indent=1, sort_keys=True)


def paint_cards():
    os.makedirs(PARK, exist_ok=True)
    man = load_manifest()
    done, skipped, refused = [], [], []
    for n in zoned_cards():
        path = os.path.join(IMG_DIR, n + '.png')
        if not os.path.exists(path):
            refused.append((n, 'missing PNG'))
            continue
        img = Image.open(path)
        mode = img.mode
        a = np.array(img.convert('RGBA'))
        if a.shape[:2] != (CARD_H, CARD_W):
            refused.append((n, 'size %dx%d' % (a.shape[1], a.shape[0])))
            continue
        if band_clean(a):
            skipped.append(n)
            continue
        try:
            out, dots = paint_out(a)
        except ValueError as e:
            refused.append((n, str(e)))
            continue
        park = os.path.join(PARK, n + '.png')
        if not os.path.exists(park):
            shutil.copy2(path, park)
        before = sha(path)
        Image.fromarray(out, 'RGBA').save(path, optimize=True)
        man['cards'][n] = {'original_sha256': man['cards'].get(n, {}).get('original_sha256', before),
                           'painted_sha256': sha(path), 'dots': dots, 'source_mode': mode}
        done.append((n, dots))
    save_manifest(man)
    return done, skipped, refused


def restore():
    man = load_manifest()
    back = 0
    for n in sorted(man.get('cards', {})):
        park = os.path.join(PARK, n + '.png')
        if os.path.exists(park):
            shutil.copy2(park, os.path.join(IMG_DIR, n + '.png'))
            back += 1
    print('restored %d original card(s) from %s' % (back, PARK))
    print('the sprites, GDT blocks and zone block are left in place; the live row then sits over the baked dots.')


# ---------------------------------------------------------------------------------
def check():
    errs = []
    for n in SPRITES:
        path = os.path.join(IMG_DIR, n + '.png')
        if not os.path.exists(path):
            errs.append('missing sprite %s.png (run --install)' % n)
            continue
        have = np.array(Image.open(path).convert('RGBA'))
        want = render(n)
        if have.shape != want.shape or not (have == want).all():
            errs.append('sprite %s.png differs from the generator (run --install)' % n)
    gdt = open(GDT, 'rb').read().decode('ascii')
    for n in SPRITES:
        if not gdt_has(gdt, n):
            errs.append('no image.gdf block for %s in tod_ui_images.gdt' % n)
    raw, nl = zone_text()
    if zone_block(nl) not in raw:
        errs.append('the generated card_pips zone block is missing or edited by hand')
    cards = zoned_cards()
    dirty = []
    for n in cards:
        path = os.path.join(IMG_DIR, n + '.png')
        if not os.path.exists(path):
            continue        # lint_tod_assets owns missing images
        a = np.array(Image.open(path).convert('RGBA'))
        if a.shape[:2] != (CARD_H, CARD_W) or not band_clean(a):
            dirty.append(n)
    if dirty:
        errs.append('%d zoned card(s) still carry BAKED level dots under the live row (run --install): %s'
                    % (len(dirty), ', '.join(dirty[:12]) + (' ...' if len(dirty) > 12 else '')))
    errs += lua_lockstep_errors()
    rows, worst = validate(PARK)
    if worst > 2.0:
        errs.append('the sprites drifted from the baked dots: mean error %.2f > 2.0' % worst)
    if errs:
        print('card_pips --check FAILED:')
        for e in errs:
            print('  - ' + e)
        return 1
    fit = ', '.join('%s %.2f' % (n.replace('i_tod_cardpip_', ''), e) for n, e in rows if e is not None)
    print('card_pips --check OK: %d sprites, GDT + zone block, %d zoned cards with no baked dots, Lua lockstep; '
          'sprite vs baked dot mean error: %s' % (len(SPRITES), len(cards), fit or 'n/a (no originals parked)'))
    return 0


# ---------------------------------------------------------------------------------
# PREVIEW: the Lua's own layout arithmetic, on the card art at card resolution
# the breathing extremes (glow alpha, glow scale, shine alpha): tod_upgrade.lua PIP.LO / PIP.HI
PULSE_LO = (0.25, 1.00, 0.00)
PULSE_HI = (0.85, 1.18, 0.40)


def plan(n, owned, gain):
    """Mirror of tod_upgrade.lua PipPlan: returns (centres_x, scale)."""
    n = max(1, min(10, n))
    if n <= 7:
        k, p = 1.0, float(PIP_PITCH)
    else:
        k = min(1.0, (PIP_USABLE_W - 3.0 * (n - 1)) / (2 * R_HALO * n))
        p = min(float(PIP_PITCH), (PIP_USABLE_W - 2 * R_HALO * k) / (n - 1))
    xs = [PIP_CX + (i - (n + 1) / 2.0) * p for i in range(1, n + 1)]
    return xs, k


def paste(canvas, sprite, cx, cy, k, alpha=1.0):
    s = Image.fromarray(sprite, 'RGBA')
    w = max(1, int(round(s.width * k)))
    if w != s.width:
        s = s.resize((w, w), Image.LANCZOS)
    if alpha < 1.0:
        arr = np.array(s)
        arr[..., 3] = (arr[..., 3] * alpha).astype(np.uint8)
        s = Image.fromarray(arr, 'RGBA')
    canvas.alpha_composite(s, (int(round(cx - w / 2.0)), int(round(cy - w / 2.0))))


def preview(out_dir):
    os.makedirs(out_dir, exist_ok=True)
    spr = {n: render(n) for n in SPRITES}
    gain_of = {1: 'i_tod_cardpip_gain_regular', 2: 'i_tod_cardpip_gain_super', 3: 'i_tod_cardpip_gain_ultimate'}
    glow_of = {1: 'i_tod_cardpip_glow_regular', 2: 'i_tod_cardpip_glow_super', 3: 'i_tod_cardpip_glow_ultimate'}
    scenes = [
        ('headshot_super_lv2of5', 'i_tod_card_headshot_super', 5, 2, 2, 2),
        ('headshot_regular_lv2of5', 'i_tod_card_headshot_regular', 5, 2, 1, 1),
        ('headshot_ultimate_lv0of5', 'i_tod_card_headshot_ultimate', 5, 0, 3, 3),
        ('damage_ultimate_lv4of10', 'i_tod_card_damage_ultimate', 10, 4, 3, 3),
        ('dmg_reduction_super_lv6of9', 'i_tod_card_dmg_reduction_super', 9, 6, 2, 2),
        ('mag_size_regular_lv2of3', 'i_tod_card_mag_size_regular', 3, 2, 1, 1),
        ('perkslots_super_lv1of5', 'i_tod_card_perkslots_super', 5, 1, 2, 2),
        ('tier_assault_2', 'i_tod_card_tier_assault_2', 3, 1, 1, 'tier'),
    ]
    sheet = []
    for tag, card, n, owned, gain, rar in scenes:
        base = Image.open(os.path.join(IMG_DIR, card + '.png')).convert('RGBA')
        for phase in ('low', 'high'):
            c = base.copy()
            xs, k = plan(n, owned, gain)
            for i, x in enumerate(xs, 1):
                if owned < i <= owned + gain:
                    g = glow_of[3 if rar == 'tier' else rar]
                    paste(c, spr[g], x, PIP_CY, k * (PULSE_HI[1] if phase == 'high' else PULSE_LO[1]), PULSE_HI[0] if phase == 'high' else PULSE_LO[0])
            for i, x in enumerate(xs, 1):
                if i <= owned:
                    name = 'i_tod_cardpip_owned'
                elif i <= owned + gain:
                    name = 'i_tod_cardpip_gain_tier' if rar == 'tier' else gain_of[rar]
                else:
                    name = 'i_tod_cardpip_empty'
                paste(c, spr[name], x, PIP_CY, k)
                if owned < i <= owned + gain and phase == 'high':
                    paste(c, spr['i_tod_cardpip_shine'], x, PIP_CY, k, PULSE_HI[2])
            # the card as drawn at 1080p (234 canvas units x 1.5 = 351 px wide)
            small = c.resize((351, 527), Image.LANCZOS)
            small.save(os.path.join(out_dir, '%s_%s_1080p.png' % (tag, phase)))
            zoom = c.crop((140, 940, 628, 1100)).resize((976, 320), Image.LANCZOS)
            zoom.save(os.path.join(out_dir, '%s_%s_zoom.png' % (tag, phase)))
            sheet.append(small)
    cols = 4
    rows = (len(sheet) + cols - 1) // cols
    W, H = 351, 527
    board = Image.new('RGBA', (cols * (W + 12) + 12, rows * (H + 12) + 12), (14, 16, 26, 255))
    for i, im in enumerate(sheet):
        board.alpha_composite(im, (12 + (i % cols) * (W + 12), 12 + (i // cols) * (H + 12)))
    board.save(os.path.join(out_dir, 'contact_sheet_1080p.png'))
    print('preview written to %s (%d scenes x low/high pulse)' % (out_dir, len(scenes)))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--install', action='store_true')
    ap.add_argument('--check', action='store_true')
    ap.add_argument('--restore', action='store_true')
    ap.add_argument('--preview', metavar='DIR')
    ap.add_argument('--dry-run', action='store_true', help='with --install: report the card pass, write nothing')
    args = ap.parse_args()
    if args.check:
        sys.exit(check())
    if args.restore:
        restore()
        return
    if args.install:
        if args.dry_run:
            for n in zoned_cards():
                a = np.array(Image.open(os.path.join(IMG_DIR, n + '.png')).convert('RGBA'))
                if band_clean(a):
                    print('  clean   %s' % n)
                    continue
                try:
                    _, dots = paint_out(a)
                    print('  paint   %s  (%d dots, panel %s)' % (n, dots, panel_colour(a)))
                except ValueError as e:
                    print('  REFUSE  %s  %s' % (n, e))
            rows, worst = validate(PARK)
            for n, e in rows:
                print('  fit     %s  %s' % (n, 'n/a' if e is None else '%.2f' % e))
            return
        rows, worst = validate(PARK)
        changed = write_sprites()
        added = write_gdt()
        zone = write_zone()
        done, skipped, refused = paint_cards()
        print('sprites written: %d (%s)' % (len(changed), ', '.join(changed) or 'all current'))
        print('GDT blocks added: %d   zone block %s' % (len(added), 'written' if zone else 'current'))
        print('cards painted: %d   already clean: %d   refused: %d' % (len(done), len(skipped), len(refused)))
        for n, why in refused:
            print('  REFUSED %s: %s' % (n, why))
        for n, e in rows:
            print('  fit %s: %s' % (n, 'n/a' if e is None else 'mean error %.2f' % e))
        print('originals parked in %s' % PARK)
        sys.exit(1 if refused else 0)
    if args.preview:
        preview(args.preview)
        return
    ap.print_help()


if __name__ == '__main__':
    main()
