// GENERATED by tools/gen_tower_map.js — DO NOT HAND-EDIT (regen instead).
// Anchor points for the CROWN finale (_tod_finale.gsc) and the crown
// upgrade terminal (_tod_upgrades.gsc). Emitted from the same tables that
// cut the crown brushes, already point-mirrored for the crown lap parity
// (LAPS=50, crown lap 51 is ODD: east stair, north hall).

#namespace tod_crown_data;

function crown_z()         { return 19392; }
function uplink_org()      { return ( -176, 368, 19392 ); }
function uplink_yaw()      { return 0; }
function dais_org()        { return ( 0, 8608, 19408 ); }
function portal_orgs()
{
	a = [];
	a[ 0 ] = ( 0, 800, 19392 );
	a[ 1 ] = ( 0, 4000, 19392 );
	a[ 2 ] = ( 0, 7360, 19392 );
	return a;
}
function causeway_gate_org() { return ( 0, 492, 19520 ); }
function beyond_gate( org )
{
	y = org[ 1 ] * 1;
	return ( y > 480 && org[ 2 ] > 18928 );
}
function crown_door_org()  { return ( 0, 7860, 19520 ); }
function in_crown( org )
{
	y = org[ 1 ] * 1;
	x = org[ 0 ] * 1;
	if ( x < -720 || x > 720 ) return false;
	if ( y < 7880 || y > 9336 ) return false;
	return ( org[ 2 ] > 19328 && org[ 2 ] < 19792 );
}
function in_hall( org )
{
	y = org[ 1 ] * 1;
	x = org[ 0 ] * 1;
	if ( x < -768 || x > 768 ) return false;
	if ( y < 7840 || y > 9376 ) return false;
	return ( org[ 2 ] > 19328 );
}
function exfil_org()       { return ( 0, 9112, 19400 ); }
function exfil_radius()    { return 96; }
function hall_center()     { return ( 0, 8608, 19392 ); }
function gate_org()        { return ( 0, 7860, 19392 ); }
function mast_tip_org()    { return ( 0, 0, 21312 ); }
function station_org()     { return ( -695, 8308, 19392 ); }
function station_trig_org(){ return ( -655, 8308, 19392 ); }
function station_yaw()     { return 90; }

// THE HALL AMMO CRATE (v12) — spawned by _tod_ammo_crate.gsc, which reads
// these instead of hardcoding, so the crate and its generator-emitted
// collision clip (label "crown hall ammo crate body") can never drift.
function crown_crate_org() { return ( 676, 8308, 19392 ); }
function crown_crate_yaw() { return 270; }

// The finale's four QUARTER-PROGRESS beacons — one ignites per quarter of
// the closing song (_tod_finale::ignite_pylon). These are the CIRCLET's
// four corner point caps, NOT anything in the hall: v11 moved the read up
// there when the user rejected the old in-room coil models ("weird looking
// pipe level model on top"). NOTE v12: the four bare PILLARS returned to
// the hall at their old +-448 spots — as pure scenery/cover with NO script
// contract. Do not point these beacons back at them; the progress read is
// the crown lighting up around you — legible from inside the hall, from
// the causeway, and from the tower. The function name is unchanged on
// purpose: _tod_finale.gsc needed a model swap, not a rewrite.
function pylon_orgs()
{
	a = [];
	a[ 0 ] = ( -2344, 7528, 23784 );
	a[ 1 ] = ( 2344, 7528, 23784 );
	a[ 2 ] = ( -2344, 11064, 23784 );
	a[ 3 ] = ( 2344, 11064, 23784 );
	return a;
}

// wall sconces (light panels) on the two long walls — parallel arrays
function sconce_orgs()
{
	a = [];
	a[ 0 ] = ( -726, 8088, 19592 );
	a[ 1 ] = ( 726, 8088, 19592 );
	a[ 2 ] = ( -726, 8296, 19592 );
	a[ 3 ] = ( 726, 8296, 19592 );
	a[ 4 ] = ( -726, 8504, 19592 );
	a[ 5 ] = ( 726, 8504, 19592 );
	a[ 6 ] = ( -726, 8712, 19592 );
	a[ 7 ] = ( 726, 8712, 19592 );
	a[ 8 ] = ( -726, 8920, 19592 );
	a[ 9 ] = ( 726, 8920, 19592 );
	a[ 10 ] = ( -726, 9128, 19592 );
	a[ 11 ] = ( 726, 9128, 19592 );
	return a;
}
function sconce_yaws()
{
	a = [];
	a[ 0 ] = 0;
	a[ 1 ] = 180;
	a[ 2 ] = 0;
	a[ 3 ] = 180;
	a[ 4 ] = 0;
	a[ 5 ] = 180;
	a[ 6 ] = 0;
	a[ 7 ] = 180;
	a[ 8 ] = 0;
	a[ 9 ] = 180;
	a[ 10 ] = 0;
	a[ 11 ] = 180;
	return a;
}
