// GENERATED by tools/gen_tower_map.js — DO NOT HAND-EDIT (regen instead).
// Anchor points for the CROWN finale (_tod_finale.gsc) and the crown
// upgrade terminal (_tod_upgrades.gsc). Emitted from the same tables that
// cut the crown brushes, already point-mirrored for the crown lap parity
// (LAPS=50, crown lap 51 is ODD: east stair, north hall).

#namespace tod_crown_data;

function crown_z()         { return 19392; }
function uplink_org()      { return ( -176, 368, 19392 ); }
function uplink_yaw()      { return 0; }
function dais_org()        { return ( 0, 8608, 19408 ); }
function portal_orgs()
{
	a = [];
	a[ 0 ] = ( 0, 800, 19392 );
	a[ 1 ] = ( 0, 4000, 19392 );
	a[ 2 ] = ( 0, 7360, 19392 );
	return a;
}
function causeway_gate_org() { return ( 0, 492, 19520 ); }
function beyond_gate( org )
{
	y = org[ 1 ] * 1;
	return ( y > 480 && org[ 2 ] > 18928 );
}
function crown_door_org()  { return ( 0, 7860, 19520 ); }
function in_crown( org )
{
	y = org[ 1 ] * 1;
	x = org[ 0 ] * 1;
	if ( x < -720 || x > 720 ) return false;
	if ( y < 7880 || y > 9336 ) return false;
	return ( org[ 2 ] > 19328 && org[ 2 ] < 19792 );
}
function in_hall( org )
{
	y = org[ 1 ] * 1;
	x = org[ 0 ] * 1;
	if ( x < -768 || x > 768 ) return false;
	if ( y < 7840 || y > 9376 ) return false;
	return ( org[ 2 ] > 19328 );
}
function exfil_org()       { return ( 0, 9112, 19400 ); }
function exfil_radius()    { return 96; }
function hall_center()     { return ( 0, 8608, 19392 ); }
function gate_org()        { return ( 0, 7860, 19392 ); }
function mast_tip_org()    { return ( 0, 0, 21312 ); }
function station_org()     { return ( -664, 8308, 19392 ); }
function station_trig_org(){ return ( -624, 8308, 19392 ); }
function station_yaw()     { return 90; }

// THE HALL AMMO CRATE (v12) — spawned by _tod_ammo_crate.gsc, which reads
// these instead of hardcoding, so the crate and its generator-emitted
// collision clip (label "crown hall ammo crate body") can never drift.
function crown_crate_org() { return ( 676, 8308, 19392 ); }
function crown_crate_yaw() { return 270; }

// The finale's four QUARTER-PROGRESS beacons — one ignites per quarter of
// the closing song (_tod_finale::ignite_pylon). These are the CIRCLET's
// four corner point caps, NOT anything in the hall: v11 moved the read up
// there when the user rejected the old in-room coil models ("weird looking
// pipe level model on top"). NOTE v12: the four bare PILLARS returned to
// the hall at their old +-448 spots — as pure scenery/cover with NO script
// contract. Do not point these beacons back at them; the progress read is
// the crown lighting up around you — legible from inside the hall, from
// the causeway, and from the tower. The function name is unchanged on
// purpose: _tod_finale.gsc needed a model swap, not a rewrite.
function pylon_orgs()
{
	a = [];
	a[ 0 ] = ( -2344, 7528, 23784 );
	a[ 1 ] = ( 2344, 7528, 23784 );
	a[ 2 ] = ( -2344, 11064, 23784 );
	a[ 3 ] = ( 2344, 11064, 23784 );
	return a;
}

// wall sconces (light panels) on the two long walls — parallel arrays
function sconce_orgs()
{
	a = [];
	a[ 0 ] = ( -726, 8088, 19592 );
	a[ 1 ] = ( 726, 8088, 19592 );
	a[ 2 ] = ( -726, 8296, 19592 );
	a[ 3 ] = ( 726, 8296, 19592 );
	a[ 4 ] = ( -726, 8504, 19592 );
	a[ 5 ] = ( 726, 8504, 19592 );
	a[ 6 ] = ( -726, 8712, 19592 );
	a[ 7 ] = ( 726, 8712, 19592 );
	a[ 8 ] = ( -726, 8920, 19592 );
	a[ 9 ] = ( 726, 8920, 19592 );
	a[ 10 ] = ( -726, 9128, 19592 );
	a[ 11 ] = ( 726, 9128, 19592 );
	return a;
}
function sconce_yaws()
{
	a = [];
	a[ 0 ] = 0;
	a[ 1 ] = 180;
	a[ 2 ] = 0;
	a[ 3 ] = 180;
	a[ 4 ] = 0;
	a[ 5 ] = 180;
	a[ 6 ] = 0;
	a[ 7 ] = 180;
	a[ 8 ] = 0;
	a[ 9 ] = 180;
	a[ 10 ] = 0;
	a[ 11 ] = 180;
	return a;
}

// --- THE FINALE BEAT SYSTEM (v12.13, docs/41) — road-derived anchors -----
// road_y: the mirrored y — compare against tide/beat y thresholds with THIS,
// never with raw org[1] (the crown lap parity flips the whole road).
function road_y( org )     { return org[ 1 ] * 1; }
// (tide_start_y/tide_end_y/road_north_yaw/tide_curtain_orgs were emitted
// here for exactly one day — THE DEREZ TIDE, added and removed 2026-08-27;
// post-mortem at the top of _tod_finale.gsc's beat table.)
// BOSS BEATS (A2): the Panzer lands at the NARROWS north lip (80 past the
// pinch exit, on full-width throat deck — fightable from the 320 throat);
// two protectors land on the gate APPROACH as the leader crosses J4.
function beat_narrows_org()        { return ( 0, 4240, 19392 ); }
function beat_narrows_trigger_y()  { return 3680; }   // leader entering the throat
function beat_flare_orgs()
{
	a = [];
	a[ 0 ] = ( -60, 7700, 19392 );
	a[ 1 ] = ( 60, 7700, 19392 );
	return a;
}
function beat_flare_trigger_y()    { return 6720; }   // leader crossing J4
// A4: the hold-out opener Panzer crashes into the hall here — clear of the
// 160 gather ring, the dais, the pillars, the crate and the station.
function siege_panzer_org()        { return ( 280, 8850, 19392 ); }
// THE CROWN'S HEARTBEAT rider: the girandole — same coordinate as its
// baked light (the ruby drop-pendant under the vortex bell).
function girandole_org()           { return ( 0, 8624, 14336 ); }
// THE COUNTDOWN AVENUE (A1): glow hosts on the 8 avenue pylon PIPS (pip
// body spans +496..+576 over the deck; host at its centre) — ignited blue
// at the buy, strobed green on the win (the tide-era red flip is gone).
function avenue_pylon_orgs()
{
	a = [];
	a[ 0 ] = ( -360, 640, 19928 );
	a[ 1 ] = ( 360, 640, 19928 );
	a[ 2 ] = ( -360, 960, 19928 );
	a[ 3 ] = ( 360, 960, 19928 );
	a[ 4 ] = ( -360, 3792, 19928 );
	a[ 5 ] = ( 360, 3792, 19928 );
	a[ 6 ] = ( -360, 4208, 19928 );
	a[ 7 ] = ( 360, 4208, 19928 );
	return a;
}
// A4 pillar count-in hosts: above each hall pillar cap (cap tops at +176;
// the baked quarter lights sit at +260 — the host at +200 splits the gap).
function hall_pillar_orgs()
{
	a = [];
	a[ 0 ] = ( -448, 8160, 19592 );
	a[ 1 ] = ( 448, 8160, 19592 );
	a[ 2 ] = ( -448, 9056, 19592 );
	a[ 3 ] = ( 448, 9056, 19592 );
	return a;
}
// THE LANE LOTTERY (B1). Parallel arrays, index = tod_lane_seal_<i>:
//   0 f1 W ridge | 1 f1 E broken stair | 2 f2 W undercroft | 3 f2 C plank | 4 f2 E weave
// seal_orgs: slab centres (FX anchors). slab/band mins+maxs: WORLD-space
// AABBs (pre-mirrored — test raw org x/y against them, no road_y). The
// BAND is the whole lane footprint fork->merge, for the riser filter.
function lane_seal_orgs()
{
	a = [];
	a[ 0 ] = ( -400, 1292, 19520 );
	a[ 1 ] = ( 400, 1292, 19520 );
	a[ 2 ] = ( -400, 4492, 19520 );
	a[ 3 ] = ( 0, 4492, 19520 );
	a[ 4 ] = ( 400, 4492, 19520 );
	return a;
}
function lane_seal_slab_mins()
{
	a = [];
	a[ 0 ] = ( -480, 1280, 0 );
	a[ 1 ] = ( 320, 1280, 0 );
	a[ 2 ] = ( -480, 4480, 0 );
	a[ 3 ] = ( -60, 4480, 0 );
	a[ 4 ] = ( 320, 4480, 0 );
	return a;
}
function lane_seal_slab_maxs()
{
	a = [];
	a[ 0 ] = ( -320, 1304, 0 );
	a[ 1 ] = ( 480, 1304, 0 );
	a[ 2 ] = ( -320, 4504, 0 );
	a[ 3 ] = ( 60, 4504, 0 );
	a[ 4 ] = ( 480, 4504, 0 );
	return a;
}
function lane_band_mins()
{
	a = [];
	a[ 0 ] = ( -800, 1280, 0 );
	a[ 1 ] = ( 320, 1280, 0 );
	a[ 2 ] = ( -800, 4480, 0 );
	a[ 3 ] = ( -60, 4480, 0 );
	a[ 4 ] = ( 320, 4480, 0 );
	return a;
}
function lane_band_maxs()
{
	a = [];
	a[ 0 ] = ( -320, 3520, 0 );
	a[ 1 ] = ( 480, 3520, 0 );
	a[ 2 ] = ( -320, 6720, 0 );
	a[ 3 ] = ( 60, 6720, 0 );
	a[ 4 ] = ( 800, 6720, 0 );
	return a;
}
