// GENERATED by tools/gen_tower_map.js — DO NOT HAND-EDIT (regen instead).
// THE ENDLESS SPIRE anchors (docs/44): door positions ride the same
// arithmetic that cut the slabs, so script and geometry cannot drift.
// Doors have NO map triggers — _tod_spire spawns them lazily in the climb
// window (the gentity-table budget, docs/44 §4).

#namespace tod_spire_data;

function spire_x()        { return 10240; }
function spire_y()        { return 0; }
function spire_laps()     { return 70; }
function spire_top()      { return 26880; }
function spire_summit_z() { return 27072; }
function door_cost()      { return 4725; }
function summit_cost()    { return 7500; }

// Is this point anywhere on the spire (arena, spiral, hubs, summit)?
function in_spire( org )
{
	return ( org[ 0 ] > 8740 && org[ 0 ] < 11740 && org[ 1 ] > -1500 && org[ 1 ] < 1500 );
}

// v14.36 — ONE DOOR PER FLOOR, TOWER-MATCHED (2 flights per door).
// Door n seals floor n. ODD floors sit on the E face (y=-256), EVEN on
// the W face (y=+256) — the tower DOORS table's own parity, because odd
// flights climb E+N and even flights W+S. (v14.23's 50 doors were all
// on the E face precisely BECAUSE they only sealed odd floors; a
// per-floor door that ignored parity would hang on the wrong side of
// the core every other floor.) Slabs are .map residents on the tower
// door contract; NO movers — the v14.1 parity mover never re-seated
// live and its un-set flags instakilled climbers (CHANGELOG v14.23).
function spire_door_count() { return 70; }
function get_spire_door_info( n )
{
	if ( n < 1 || n > 70 )
		return undefined;
	b = ( n - 1 ) * 384;
	info = SpawnStruct();
	if ( ( n % 2 ) == 1 )
		info.org = ( 10576, -256, b + 40 );
	else
		info.org = ( 9904, 256, b + 40 );
	info.off = ( 0, 60, 0 );
	info.cost = 4725;
	info.flag = "enter_spire" + n;
	info.target = "tod_spire_door" + n;
	info.floor = n;
	info.dest = "the Spire - Floor " + n;
	return info;
}
function spire_door_z( n ) { return ( n - 1 ) * 384; }

// v14.31 — THE HONOUR GUARD anchor: the MID landing of the floor door n
// just opened — the same landing that floor's own risers use, hence
// proven-open ground. v14.36: parity-aware, because per-floor doors
// alternate faces (odd -> NE at +336,+336; even -> SW at -336,-336,
// mirroring the riser table in section 6f).
// _tod_spire hands this to spawn_panzer as tod_boss_force_org; that
// path still runs pick_spawn_point + ground_snap, so this is a HINT,
// not a teleport — a blocked anchor scatters rather than stacking.
function guard_spawn_org( n )
{
	mid = ( n - 1 ) * 384 + 192;
	if ( ( n % 2 ) == 1 )
		return ( 10576, 336, mid );
	return ( 9904, -336, mid );
}

// Crate shelf per floor (floors 5+; hub floors use the hub crate; the
// arena crate covers 1-4). undefined = no shelf on that floor.
//
// ⚠️ THE UPPER BOUND IS LOAD-BEARING (v17.83, user 2026-09-05: "lingering
// ammo crates about the spire on floor 70 ... looking up during boss fight
// and I swear i saw some leftover crate models"). This is a FORMULA, not a
// table, and it had no ceiling: _tod_spire::crate_window materialises every
// floor within TOD_SPIRE_CRATE_WINDOW of a player and trusts an `isdefined`
// on this return. On the summit deck the player reads as floor
// 71, so the window asked for 72..74 — and this function
// happily returned coordinates for floors that have no shelf, no landing and
// no tower: three crate models hanging in the sky over the boss fight.
//
// It was invisible until v17.69 cut the spire from 100 laps to 70: at 100
// laps those floors had real shelves. Same class as the sun volume (docs/107)
// — a DERIVED value that did not follow the lap-count cut. When SP_LAPS moves,
// grep for every unbounded per-floor formula in this emitter, not just this one.
function shelf_crate_org( n )
{
	if ( n < 5 || n > 70 || ( n % 10 ) == 0 || ( n % 10 ) == 1 )   // v16.19: no shelf on a hub floor or the floor after it (inside the drum); v17.83: none above the top floor
		return undefined;
	mid = ( n - 1 ) * 384 + 192;
	if ( ( n % 2 ) == 1 )
		return ( 10766, 336, mid );
	return ( 9714, -336, mid );
}
// Yaws from the generator's one crate contract (CRATE_YAW_*: front = yaw + 90).
// Odd shelves hang EAST of the NE landing and face WEST back onto it; even
// shelves are the mirror. The arena crate backs the S wall and faces NORTH.
// The v14.23 "flip all four" was the right call and this is its record.
function shelf_crate_yaw( n ) { return ( ( ( n % 2 ) == 1 ) ? 90 : 270 ); }
function arena_crate_org() { return ( 10040, -500, 0 ); }
function arena_crate_yaw() { return 0; }

// THE WARDEN TRIALS — THE HUB HALL (v16.19 / v16.21): anchors around the tower
// axis, even frame (every hub lap is even, asserted in the generator).
// trial_box is the HALL ONLY (v16.21): the drum footprint north of the S
// lane, MINUS the W flight's slot (the notch) and MINUS the next lap's E
// flight beyond door n+1 — in_box applies both exclusions. The gate is the
// HALL GATE across the porch's mouth (hidden until the trial). Every hub
// has its own layout: the mark (where the Max Ammo lands) and the Warden
// drop point come from it.
function hub_every() { return 10; }
function is_hub( n ) { return ( n >= 10 && n <= 70 && ( n % 10 ) == 0 ); }
// The hub whose trial guards door n (door n opens the floor ABOVE hub n-1),
// or 0 when door n is not a trial door.
function trial_hub_of_door( n )
{
	if ( n > 1 && is_hub( n - 1 ) )
		return ( n - 1 );
	return 0;
}
function trial_gate_target( hub ) { return "tod_spire_hall_gate" + hub; }
// z = hub_z (the hall floor = the mid landing).
function trial_box( z )
{
	b = SpawnStruct();
	b.x1 = 9784;
	b.x2 = 10696;
	b.y1 = -456;   // v18.78: the SE alcove (east of the S lane's end wall, south of -CORE) is IN; the S lane + SW landing are exclusion 3
	b.y2 = 456;
	b.z1 = z - 88;   // under the porch's lowest step
	b.z2 = z + 292;
	// exclusion 1: the E lane past door n+1 (the next lap's E flight)
	b.ex1 = 10476;
	b.ex2 = 10696;
	b.ey1 = -246;
	b.ey2 = 456;
	b.ez1 = z + 182;
	b.ez2 = z + 492;
	// exclusion 2: the W flight's slot (the notch) — outside the hall gate —
	// PLUS the gate's own thickness and a player's radius (40 past the x=-256
	// line): nobody standing in the slab's volume may count as "in", or the
	// seal closes on them (v16.26 review find)
	b.nx1 = 9784;
	b.nx2 = 10024;
	b.ny1 = -266;
	b.ny2 = 64;
	// exclusion 3 (v18.78): the S lane + the SW landing, outside the seal. y1 used
	// to stop at -CORE, which ALSO cut out the SE ALCOVE under the SE landing: no
	// riser, no elite landing and no player ever counted there, which made it
	// the safest spot in every hall (tools/lint_tod_hall_bunkers.js).
	b.sx1 = 9784;
	b.sx2 = 10476;
	b.sy1 = -456;
	b.sy2 = -256;
	// exclusion 4 (2026-09-10, first play of the open halls: "zombies spawning outside"
	// + "elites and panzers freezing"): everything ABOVE the alcove roof in the SE corner.
	// The SE LANDING (lap n+1's start, 192 up) is outside the seal — reached only up the
	// S flight from the SW landing, behind door n+1 — and it carries a riser at (336,-336).
	// v18.78 let it in with the alcove: a zombie rising there was stranded outside the
	// gate, and pick_spawn_point could stand an elite there with no route to anyone.
	// The alcove floor is at z; its roof (the landing slab) at z + 176 — so the cut starts
	// at z + 100 and covers the S flight's top treads east of the lane wall too.
	b.tx1 = 10476;
	b.tx2 = 10696;
	b.ty1 = -456;
	b.ty2 = -246;
	b.tz1 = z + 100;
	b.tz2 = z + 492;
	return b;
}
function in_box( org, b )
{
	if ( !( org[ 0 ] > b.x1 && org[ 0 ] < b.x2 && org[ 1 ] > b.y1 && org[ 1 ] < b.y2 && org[ 2 ] > b.z1 && org[ 2 ] < b.z2 ) )
		return false;
	if ( isdefined( b.ex1 ) && org[ 0 ] > b.ex1 && org[ 0 ] < b.ex2 && org[ 1 ] > b.ey1 && org[ 1 ] < b.ey2 && org[ 2 ] > b.ez1 && org[ 2 ] < b.ez2 )
		return false;
	if ( isdefined( b.nx1 ) && org[ 0 ] > b.nx1 && org[ 0 ] < b.nx2 && org[ 1 ] > b.ny1 && org[ 1 ] < b.ny2 )
		return false;
	if ( isdefined( b.sx1 ) && org[ 0 ] > b.sx1 && org[ 0 ] < b.sx2 && org[ 1 ] > b.sy1 && org[ 1 ] < b.sy2 )
		return false;
	if ( isdefined( b.tx1 ) && org[ 0 ] > b.tx1 && org[ 0 ] < b.tx2 && org[ 1 ] > b.ty1 && org[ 1 ] < b.ty2 && org[ 2 ] > b.tz1 && org[ 2 ] < b.tz2 )
		return false;
	return true;
}
// per-hub layout anchors (SP_RM_LAYOUTS): index = hub / hub_every - 1
function trial_layout_index( hub ) { return ( int( hub / hub_every() ) - 1 ); }
function trial_mark_org( hub, z )
{
	switch ( trial_layout_index( hub ) )
	{
		case 0: return ( 10330, 140, z + 48 );   // THE RING
		case 1: return ( 10220, -160, z + 0 );   // THE KENNEL
		case 2: return ( 10240, 344, z + 48 );   // THE FIRING LINE
		case 3: return ( 10300, 40, z + 48 );   // THE ALTAR
		case 4: return ( 10330, 110, z + 0 );   // THE MAZE
		case 5: return ( 10180, -190, z + 0 );   // THE GAUNTLET
		case 6: return ( 10310, 20, z + 0 );   // THE THRONE
	}
	return ( 10240, 0, z );
}
function trial_warden_org( hub, z )
{
	switch ( trial_layout_index( hub ) )
	{
		case 0: return ( 10330, 140, z + 48 );   // THE RING
		case 1: return ( 10380, -190, z + 0 );   // THE KENNEL
		case 2: return ( 10300, -72, z + 0 );   // THE FIRING LINE
		case 3: return ( 10300, 40, z + 48 );   // THE ALTAR
		case 4: return ( 9900, 160, z + 0 );   // THE MAZE
		case 5: return ( 10610, 370, z + 12 );   // THE GAUNTLET
		case 6: return ( 10310, 300, z + 72 );   // THE THRONE
	}
	return ( 10240, 100, z );
}
// the hall gate's centre at hall-floor level (the FX hosts stand along it);
// it runs along y, so hosts spread on y and face +x (into the hall).
function trial_gate_org( z )   { return ( 9984, -166, z ); }
function trial_gate_len()      { return 140; }
function trial_gate_axis()     { return ( 0, 1, 0 ); }
function trial_gate_yaw()      { return 0; }

// vendor hubs (every 10th floor, even frame) — on the hub hall's walls since v16.19;
// v18.78: PER HUB (SP_RM_LAYOUTS[i].furn — which wall each vendor stands on). index = hub / hub_every - 1
function hub_laps() { return array( 10, 20, 30, 40, 50, 60, 70 ); }
function hub_z( lap ) { return ( lap - 1 ) * 384 + 192; }
function hub_pap_org( hub, z )
{
	switch ( trial_layout_index( hub ) )
	{
		case 0: return ( 9824, 200, z );   // THE RING (W wall PaP, E wall crate)
		case 1: return ( 10656, -200, z );   // THE KENNEL (E wall PaP, W wall crate)
		case 2: return ( 10656, -200, z );   // THE FIRING LINE (E wall PaP, S wall crate)
		case 3: return ( 10656, -160, z );   // THE ALTAR (E wall PaP, W wall crate)
		case 4: return ( 10440, -216, z );   // THE MAZE (S wall PaP, W wall crate)
		case 5: return ( 10120, 416, z );   // THE GAUNTLET (N wall PaP, S wall crate)
		case 6: return ( 9824, 200, z );   // THE THRONE (W wall PaP, S wall crate)
	}
	return ( 9824, 200, z );
}
function hub_pap_trig( hub, z )
{
	switch ( trial_layout_index( hub ) )
	{
		case 0: return ( 9880, 200, z );   // THE RING (W wall PaP, E wall crate)
		case 1: return ( 10600, -200, z );   // THE KENNEL (E wall PaP, W wall crate)
		case 2: return ( 10600, -200, z );   // THE FIRING LINE (E wall PaP, S wall crate)
		case 3: return ( 10600, -160, z );   // THE ALTAR (E wall PaP, W wall crate)
		case 4: return ( 10440, -160, z );   // THE MAZE (S wall PaP, W wall crate)
		case 5: return ( 10120, 360, z );   // THE GAUNTLET (N wall PaP, S wall crate)
		case 6: return ( 9880, 200, z );   // THE THRONE (W wall PaP, S wall crate)
	}
	return ( 9880, 200, z );
}
function hub_pap_yaw( hub )
{
	switch ( trial_layout_index( hub ) )
	{
		case 0: return 90;   // THE RING (W wall PaP, E wall crate)
		case 1: return 270;   // THE KENNEL (E wall PaP, W wall crate)
		case 2: return 270;   // THE FIRING LINE (E wall PaP, S wall crate)
		case 3: return 270;   // THE ALTAR (E wall PaP, W wall crate)
		case 4: return 180;   // THE MAZE (S wall PaP, W wall crate)
		case 5: return 359.999;   // THE GAUNTLET (N wall PaP, S wall crate)
		case 6: return 90;   // THE THRONE (W wall PaP, S wall crate)
	}
	return 90;
}
function hub_crate_org( hub, z )
{
	switch ( trial_layout_index( hub ) )
	{
		case 0: return ( 10636, -180, z );   // THE RING (W wall PaP, E wall crate)
		case 1: return ( 9844, 160, z );   // THE KENNEL (E wall PaP, W wall crate)
		case 2: return ( 10300, -196, z );   // THE FIRING LINE (E wall PaP, S wall crate)
		case 3: return ( 9844, 116, z );   // THE ALTAR (E wall PaP, W wall crate)
		case 4: return ( 9844, 300, z );   // THE MAZE (S wall PaP, W wall crate)
		case 5: return ( 10426, -196, z );   // THE GAUNTLET (N wall PaP, S wall crate)
		case 6: return ( 10440, -196, z );   // THE THRONE (W wall PaP, S wall crate)
	}
	return ( 10636, 120, z );
}
function hub_crate_yaw( hub )
{
	switch ( trial_layout_index( hub ) )
	{
		case 0: return 90;   // THE RING (W wall PaP, E wall crate)
		case 1: return 270;   // THE KENNEL (E wall PaP, W wall crate)
		case 2: return 0;   // THE FIRING LINE (E wall PaP, S wall crate)
		case 3: return 270;   // THE ALTAR (E wall PaP, W wall crate)
		case 4: return 270;   // THE MAZE (S wall PaP, W wall crate)
		case 5: return 0;   // THE GAUNTLET (N wall PaP, S wall crate)
		case 6: return 0;   // THE THRONE (W wall PaP, S wall crate)
	}
	return 90;
}
// (hub_perk_pads / hub_perk_yaw / hub_perk_front / arena_perk_pads — RETIRED
// v17.56: the spire sells no perks, every perk is perma-granted on ascension.)

// arrival + summit
function arrival_org()     { return ( 9840, 0, 0 ); }   // west-band centre — NEVER inside |x|<256 (the core column)
function summit_exfil_org(){ return ( 10240, -150, 27096 ); }
// THE ROCKET (docs/170, _tod_rocket.gsc): the crash, the wreck, the arrival facing it
function rocket_crash_tip()          { return ( 9780, 470, 6 ); }
function rocket_wreck_org()          { return ( 9669.58, 561.88, 400.67 ); }
function rocket_wreck_angles()       { return ( 70, -39.76, 17 ); }
function rocket_arrival_yaw()        { return 102.4; }
function summit_box()
{
	b = SpawnStruct();
	b.x1 = 9536;
	b.x2 = 10944;
	b.y1 = -704;
	b.y2 = 704;
	b.z1 = 27032;
	b.z2 = 27472;
	// exclusion: the stair well + the gate's volume + a player radius north of it
	b.ex1 = 10456;
	b.ex2 = 10716;
	b.ey1 = -296;
	b.ey2 = 310;
	b.ez1 = 26872;
	b.ez2 = 27372;
	return b;
}
function summit_gate_target() { return "tod_spire_summit_gate"; }
function summit_gate_org()    { return ( 10586, 262, 27072 ); }
function summit_gate_len()    { return 180; }
function summit_gate_axis()   { return ( 1, 0, 0 ); }
function summit_gate_yaw()    { return 90; }
function summit_king_org()    { return ( 9840, 0, 27088 ); }
function summit_mark_org()    { return ( 9940, -300, 27088 ); }
function summit_crate_org()   { return ( 9574, -320, 27088 ); }
function summit_crate_yaw()   { return 270; }
function beacon_org()      { return ( 10240, 0, 27608 ); }

// THE ASCENSION PAD — on the crown hall DAIS (the focal point the uplink
// left behind in v10). Crown-frame coordinates, pre-mirrored like every
// _tod_crown_data anchor.
function ascension_pad_org() { return ( 0, 8608, 19408 ); }
function ascension_pad_yaw() { return 180; }

// zone bookkeeping for the wiring (zonemgr adjacency, spawn filter)
function zone_chunk() { return 5; }
function spire_zone_of( n ) { return "spire_c" + ( int( ( n - 1 ) / 5 ) + 1 ) + "_zone"; }
function spire_zone_names()
{
	a = [];
	a[ 0 ] = "spire_base_zone";
	a[ 1 ] = "spire_c1_zone";
	a[ 2 ] = "spire_c2_zone";
	a[ 3 ] = "spire_c3_zone";
	a[ 4 ] = "spire_c4_zone";
	a[ 5 ] = "spire_c5_zone";
	a[ 6 ] = "spire_c6_zone";
	a[ 7 ] = "spire_c7_zone";
	a[ 8 ] = "spire_c8_zone";
	a[ 9 ] = "spire_c9_zone";
	a[ 10 ] = "spire_c10_zone";
	a[ 11 ] = "spire_c11_zone";
	a[ 12 ] = "spire_c12_zone";
	a[ 13 ] = "spire_c13_zone";
	a[ 14 ] = "spire_c14_zone";
	a[ 15 ] = "spire_summit_zone";
	return a;
}
