// GENERATED by tools/gen_tower_map.js — DO NOT HAND-EDIT (regen instead).
// v13 breather-lounge furniture anchors. Source of truth: the BR_FURN table
// in the generator, which asserts every pair of use-triggers clears by
// radius_a + radius_b + 64 at generation time — the mechanical form of the
// v10.4 rule, added after the shipped PaP/crate pair sat 174u apart with a
// 38u rim gap and players bought the wrong 5000-point thing.
// Frame: EVEN/mirrored (all four breathers). z = the lounge mid-slab top.

#namespace tod_breather_data;

// mid-slab z of each breather lounge, ascending (laps 10/20/30/40)
function breather_zs() { return array( 3648, 7488, 11328, 15168 ); }

// PACK-A-PUNCH — W wall, facing east into the room
function pap_org( z ) { return ( -744, -680, z ); }
function pap_trig( z ) { return ( -688, -680, z ); }
function pap_yaw() { return 90; }

// UPGRADE STATION — N wall (entrance side), facing south into the room
function station_org( z ) { return ( -500, -460, z ); }
function station_trig( z ) { return ( -500, -516, z ); }
function station_yaw() { return 359.999; }

// AMMO CRATE — E wall, facing west (its collision clip in the .map is cut
// from this same origin: label "ammo crate body", lint MODEL_CLIP_COLUMNS)
function crate_org( z ) { return ( -310, -700, z ); }
function crate_yaw() { return 270; }

// BASE AMMO CRATE — core WEST face at the base arena, ABSOLUTE coords (no
// mirror frame; the base is authored absolute). v14.3: origin lives in the
// generator (BASE_CRATE), which also cuts its "base ammo crate body" clip
// brush and asserts it clear of the lap-1 E flight — the Workshop navmesh
// report (Pinkbrotha4310 2026-08-30) is the reason this rides the no-drift
// contract instead of a hand-typed GSC literal.
function base_crate_org() { return ( -320, 0, 0 ); }
function base_crate_yaw() { return 270; }

// TELEPORTER — the pad out on the spur platform, and where up-riders land
// (160u up the gantry toward the room: outside the pad's 120u gather,
// so an arrival is never swept along by the next departure — v10.4 rule)
function tp_pad_org( z ) { return ( -704, -1456, z ); }
function tp_arrival_org( z ) { return ( -704, -1296, z ); }
