// GENERATED by tools/gen_tower_map.js — DO NOT HAND-EDIT (regen instead).
// Door buy-trigger positions for _tod_doors.gsc. A map brush entity has no
// usable .origin (reports 0,0,0), so the generator hardcodes each doorway
// center + its thin-axis offset here from the same tables that cut the .map.

#namespace tod_door_data;

function get_door_info( flag )
{
	info = SpawnStruct();
	switch ( flag )
	{
	case "enter_lap1":
		info.org = ( 336, -256, 40 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 1";
		info.cost = 750;
		return info;
	case "enter_lap2":
		info.org = ( -336, 256, 424 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 2";
		info.cost = 810;
		return info;
	case "enter_lap3":
		info.org = ( 336, -256, 808 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 3";
		info.cost = 870;
		return info;
	case "enter_lap4":
		info.org = ( -336, 256, 1192 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 4";
		info.cost = 930;
		return info;
	case "enter_lap5":
		info.org = ( 336, -256, 1576 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 5";
		info.cost = 990;
		return info;
	case "enter_lap6":
		info.org = ( -336, 256, 1960 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 6";
		info.cost = 1050;
		return info;
	case "enter_lap7":
		info.org = ( 336, -256, 2344 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 7";
		info.cost = 1110;
		return info;
	case "enter_lap8":
		info.org = ( -336, 256, 2728 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 8";
		info.cost = 1170;
		return info;
	case "enter_lap9":
		info.org = ( 336, -256, 3112 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 9";
		info.cost = 1230;
		return info;
	case "enter_lap10":
		info.org = ( -336, 256, 3496 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 10";
		info.cost = 1290;
		return info;
	case "enter_lap11":
		info.org = ( 336, -256, 3880 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 11";
		info.cost = 1350;
		return info;
	case "enter_lap12":
		info.org = ( -336, 256, 4264 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 12";
		info.cost = 1410;
		return info;
	case "enter_lap13":
		info.org = ( 336, -256, 4648 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 13";
		info.cost = 1470;
		return info;
	case "enter_lap14":
		info.org = ( -336, 256, 5032 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 14";
		info.cost = 1530;
		return info;
	case "enter_lap15":
		info.org = ( 336, -256, 5416 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 15";
		info.cost = 1590;
		return info;
	case "enter_lap16":
		info.org = ( -336, 256, 5800 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 16";
		info.cost = 1650;
		return info;
	case "enter_lap17":
		info.org = ( 336, -256, 6184 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 17";
		info.cost = 1710;
		return info;
	case "enter_lap18":
		info.org = ( -336, 256, 6568 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 18";
		info.cost = 1770;
		return info;
	case "enter_lap19":
		info.org = ( 336, -256, 6952 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 19";
		info.cost = 1830;
		return info;
	case "enter_lap20":
		info.org = ( -336, 256, 7336 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 20";
		info.cost = 1890;
		return info;
	case "enter_lap21":
		info.org = ( 336, -256, 7720 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 21";
		info.cost = 1950;
		return info;
	case "enter_lap22":
		info.org = ( -336, 256, 8104 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 22";
		info.cost = 2010;
		return info;
	case "enter_lap23":
		info.org = ( 336, -256, 8488 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 23";
		info.cost = 2070;
		return info;
	case "enter_lap24":
		info.org = ( -336, 256, 8872 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 24";
		info.cost = 2130;
		return info;
	case "enter_lap25":
		info.org = ( 336, -256, 9256 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 25";
		info.cost = 2190;
		return info;
	case "enter_lap26":
		info.org = ( -336, 256, 9640 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 26";
		info.cost = 2250;
		return info;
	case "enter_lap27":
		info.org = ( 336, -256, 10024 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 27";
		info.cost = 2310;
		return info;
	case "enter_lap28":
		info.org = ( -336, 256, 10408 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 28";
		info.cost = 2370;
		return info;
	case "enter_lap29":
		info.org = ( 336, -256, 10792 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 29";
		info.cost = 2430;
		return info;
	case "enter_lap30":
		info.org = ( -336, 256, 11176 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 30";
		info.cost = 2490;
		return info;
	case "enter_lap31":
		info.org = ( 336, -256, 11560 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 31";
		info.cost = 2550;
		return info;
	case "enter_lap32":
		info.org = ( -336, 256, 11944 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 32";
		info.cost = 2610;
		return info;
	case "enter_lap33":
		info.org = ( 336, -256, 12328 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 33";
		info.cost = 2670;
		return info;
	case "enter_lap34":
		info.org = ( -336, 256, 12712 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 34";
		info.cost = 2730;
		return info;
	case "enter_lap35":
		info.org = ( 336, -256, 13096 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 35";
		info.cost = 2790;
		return info;
	case "enter_lap36":
		info.org = ( -336, 256, 13480 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 36";
		info.cost = 2850;
		return info;
	case "enter_lap37":
		info.org = ( 336, -256, 13864 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 37";
		info.cost = 2910;
		return info;
	case "enter_lap38":
		info.org = ( -336, 256, 14248 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 38";
		info.cost = 2970;
		return info;
	case "enter_lap39":
		info.org = ( 336, -256, 14632 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 39";
		info.cost = 3000;
		return info;
	case "enter_lap40":
		info.org = ( -336, 256, 15016 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 40";
		info.cost = 3000;
		return info;
	case "enter_lap41":
		info.org = ( 336, -256, 15400 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 41";
		info.cost = 3000;
		return info;
	case "enter_lap42":
		info.org = ( -336, 256, 15784 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 42";
		info.cost = 3000;
		return info;
	case "enter_lap43":
		info.org = ( 336, -256, 16168 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 43";
		info.cost = 3000;
		return info;
	case "enter_lap44":
		info.org = ( -336, 256, 16552 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 44";
		info.cost = 3000;
		return info;
	case "enter_lap45":
		info.org = ( 336, -256, 16936 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 45";
		info.cost = 3000;
		return info;
	case "enter_lap46":
		info.org = ( -336, 256, 17320 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 46";
		info.cost = 3000;
		return info;
	case "enter_lap47":
		info.org = ( 336, -256, 17704 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 47";
		info.cost = 3000;
		return info;
	case "enter_lap48":
		info.org = ( -336, 256, 18088 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 48";
		info.cost = 3000;
		return info;
	case "enter_lap49":
		info.org = ( 336, -256, 18472 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 49";
		info.cost = 3000;
		return info;
	case "enter_lap50":
		info.org = ( -336, 256, 18856 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Spiral - Floor 50";
		info.cost = 3000;
		return info;
	case "enter_roof":
		info.org = ( 336, -256, 19240 );
		info.off = ( 0, 60, 0 );
		info.dest = "the Crown";
		info.cost = 7500;
		return info;
	case "enter_power":
		info.org = ( 270, -480, 40 );
		info.off = ( 60, 0, 0 );
		info.dest = "the Power Room";
		info.cost = 750;
		return info;
	case "enter_tpbay":
		info.org = ( 0, -550, 40 );
		info.off = ( 0, 20, 0 );
		info.dest = "the Teleport Bay";
		info.cost = 1500;
		return info;
	}
	return undefined;
}
