// tools/gen_tod_amp63.js — the slasher's T1 sidearm, the AMP63, as a MAP-OWNED copy
// (2026-10-04, user: "increase the reload time on the slashe secondaries by 30% all
// of them").
//
// WHY A COPY. The AMP63 is a RAW PORT: its three weapon assets (t9_amp63, and the
// akimbo PaP pair t9_amp63_rdw_up_zm / t9_amp63_ldw_up_zm) live in the install-side
// <tools>/source_data/skye_t9_amp63.gdt, and that file is SHARED - Tower of Doom II
// (zm_tod2_cybercity, zm_tower_of_doom_ii) zones the same three assets. Editing it in
// place would slow Tower II's reloads too, and a Mod Tools "verify" would silently
// revert it here. The UDM and RK7 (T2/T3) are already generated by gen_tod_twins.js;
// the AMP63 could not go through that pipeline without picking up every roster-wide
// transform (secondary damage x0.75, +1 magazine, LOC_NORM, the sidearm ladder) on a
// gun nobody asked to retune.
//
// SO THIS TOOL COPIES THE THREE BLOCKS VERBATIM and changes exactly two things:
//   1. NAMES, onto the map's own "_b" sidearm convention (the Executioner's shape):
//        t9_amp63            -> t9_amp63_b
//        t9_amp63_rdw_up_zm  -> t9_amp63_rdw_up_b_zm   (runtime t9_amp63_rdw_up_b)
//        t9_amp63_ldw_up_zm  -> t9_amp63_ldw_up_b_zm   (runtime t9_amp63_ldw_up_b)
//      and the two DualWieldWeapon cross-references, which hold the RUNTIME name
//      (the engine appends _zm itself - zm_tower_of_doom.zone's AMP63 note).
//      Every name still CONTAINS "t9_amp63", so every substring lookup keeps
//      matching without an edit: the class stem (TOD_SECSTEM_SLASHER_1), the
//      script damage multiplier (_tod_upgrades gun_balance_mult), the HUD icon
//      table (AetheriumLoadout TOD_GUN_CAT). parentWeaponName is a label, not a
//      reference, and stays the port's (the generated twins do the same).
//   2. EVERY RELOAD TIME (every "reload...Time" key) x TOD_AMP63_RELOAD_MULT, on all
//      three blocks - base and both PaP hands. LOCKSTEP with gen_tod_twins.js
//      SLASHER_SEC_RELOAD_MULT (the UDM and RK7 take the same factor there).
//
// LEDGER-NEUTRAL: the zone trades its three stock weapon lines for these three.
// The source is SHA-PINNED: if the shared file ever changes (a Mod Tools verify, a
// Tower II edit), this tool refuses rather than ship a different gun quietly. Read
// the change, then update SRC_SHA256.
//
// Usage:  node tools/gen_tod_amp63.js           write source_data/tod_amp63.gdt
//         node tools/gen_tod_amp63.js --check   build gate: the repo file == a fresh generation
'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const REPO = path.join(__dirname, '..');
const TOOLS = 'C:/Program Files (x86)/Steam/steamapps/common/Call of Duty Black Ops III 455130';
const SRC = path.join(TOOLS, 'source_data', 'skye_t9_amp63.gdt');
const OUT = path.join(REPO, 'source_data', 'tod_amp63.gdt');
// skye_t9_amp63.gdt as it shipped through v19.72 (the tod dual-wield + reserve edits,
// map 1's hip-spread edit). 2026-10-04.
const SRC_SHA256 = 'a983b8e49d3dc85b6bc5ff55d76e5d9308effb9786ee3204c9dffcc52ed0ec8a';
const TOD_AMP63_RELOAD_MULT = 1.3;   // LOCKSTEP gen_tod_twins.js SLASHER_SEC_RELOAD_MULT

const BLOCKS = [
  { from: 't9_amp63',           to: 't9_amp63_b',           gdf: 'bulletweapon.gdf',    dual: '' },
  { from: 't9_amp63_rdw_up_zm', to: 't9_amp63_rdw_up_b_zm', gdf: 'bulletweapon.gdf',    dual: 't9_amp63_ldw_up_b' },
  { from: 't9_amp63_ldw_up_zm', to: 't9_amp63_ldw_up_b_zm', gdf: 'dualwieldweapon.gdf', dual: 't9_amp63_rdw_up_b' },
];
const RELOAD_KEY = /^reload[A-Za-z]*Time$/;

function fmt(n) {
  if (Number.isInteger(n)) return String(n);
  return parseFloat(n.toFixed(4)).toString();
}

function generate() {
  if (!fs.existsSync(SRC)) throw new Error(`gen_tod_amp63: missing ${SRC}`);
  const buf = fs.readFileSync(SRC);
  const sha = crypto.createHash('sha256').update(buf).digest('hex');
  if (sha !== SRC_SHA256)
    throw new Error(`gen_tod_amp63: ${path.basename(SRC)} changed (sha256 ${sha}, pinned ${SRC_SHA256}).\n` +
      '  It is shared with Tower of Doom II and lives outside this repo. Diff it against its\n' +
      '  .tod-dualwield-orig / .tod-reserve-orig backups, decide, then update SRC_SHA256.');
  const lines = buf.toString('utf8').split(/\r?\n/);
  const out = ['{'];
  const report = [];
  for (const b of BLOCKS) {
    const head = `\t"${b.from}" ( "${b.gdf}" )`;
    const i = lines.indexOf(head);
    if (i < 0 || lines.indexOf(head, i + 1) >= 0) throw new Error(`gen_tod_amp63: expected exactly one block ${head.trim()}`);
    if (lines[i + 1] !== '\t{') throw new Error(`gen_tod_amp63: ${b.from}: no opening brace`);
    let j = i + 2;
    while (j < lines.length && lines[j] !== '\t}') j++;
    if (j >= lines.length) throw new Error(`gen_tod_amp63: ${b.from}: no closing brace`);
    out.push(`\t"${b.to}" ( "${b.gdf}" )`, '\t{');
    let dualSeen = 0, scaled = 0;
    for (const ln of lines.slice(i + 2, j)) {
      const m = ln.match(/^(\t\t)"([A-Za-z0-9_]+)" "([^"]*)"$/);
      if (!m) throw new Error(`gen_tod_amp63: ${b.from}: unexpected line ${JSON.stringify(ln)}`);
      const [, ind, key, val] = m;
      if (key === 'DualWieldWeapon') {
        dualSeen++;
        out.push(`${ind}"${key}" "${b.dual}"`);
        continue;
      }
      if (RELOAD_KEY.test(key)) {
        const v = parseFloat(val);
        if (!Number.isFinite(v)) throw new Error(`gen_tod_amp63: ${b.from}.${key} is not a number (${val})`);
        if (v !== 0) {
          const nv = fmt(v * TOD_AMP63_RELOAD_MULT);
          report.push(`${b.to}.${key} ${val} -> ${nv}`);
          out.push(`${ind}"${key}" "${nv}"`);
          scaled++;
          continue;
        }
      }
      out.push(ln);
    }
    if (dualSeen !== 1) throw new Error(`gen_tod_amp63: ${b.from}: expected one DualWieldWeapon field, saw ${dualSeen}`);
    if (scaled === 0) throw new Error(`gen_tod_amp63: ${b.from}: no reload time scaled - the port's reload keys moved?`);
    out.push('\t}');
  }
  out.push('}', '');
  return { text: out.join('\r\n'), report };
}

function main() {
  const { text, report } = generate();
  if (process.argv.includes('--check')) {
    const have = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : null;
    if (have !== text) {
      console.error(`gen_tod_amp63 --check FAILED: ${path.relative(REPO, OUT)} is not what the tool generates. Run: node tools/gen_tod_amp63.js`);
      process.exit(1);
    }
    console.log(`gen_tod_amp63 --check OK: 3 map-owned AMP63 blocks, ${report.length} reload times x${TOD_AMP63_RELOAD_MULT}`);
    return;
  }
  fs.writeFileSync(OUT, text);
  for (const r of report) console.log('  ' + r);
  console.log(`wrote ${path.relative(REPO, OUT)} (3 weapon assets, ${report.length} reload times x${TOD_AMP63_RELOAD_MULT})`);
}

main();
