"""Third-person staff models render ONE full-detail LOD (docs/167 item 4).

Lead tester, 2026-10-01: "Parts of the staff float invisibly in the hand 90% of
the time, only appearing when getting close. So it just looks like multiple
floating pieces."

WHY. The world (third-person) staff is a SHAFT model plus a HEAD attached at its
tag. The Sep 27 assembly pass (tools/build_staff_assembly.py) took the heads off
the donor's generated LOD chain - "Keep every small head/crystal part in one
full-detail LOD" - and they compile with lodCount 1. The SHAFT kept the donor's
autogenerated 50 / 25 / 12 / 7 / 4 percent chain: the compiled ledger
(zm_tower_of_doom_xmodel.csv) shows tod_staff_world at 6 LODs, 10,424 triangles
down to 415, and the ice staff's world body / tips the same. Decimating a long
thin shaft to a quarter of its triangles erases it, so past the first switch
distance a teammate's staff is a full-detail head floating at their hand - the
report, word for word. Only getting close (LOD0) brings the shaft back.

FIX. These four WORLD models take the heads' rule: every autogen switch off, so
each compiles to its single full-detail LOD. View models are untouched (a
first-person model never leaves LOD0). Nothing else in either GDT moves: the
edit is in place, byte for byte outside the switched values, and the one
manifest that pins tod_staff_pap.gdt (docs/staff_presentation_manifest.json) is
re-stamped - the same in-place refresh tools/staff_presentation_bindings.py uses.

  python tools/staff_world_lods.py                    apply (idempotent)
  python tools/staff_world_lods.py --check            source gate (build_map.ps1)
  python tools/staff_world_lods.py --compiled-ledger <zm_tower_of_doom_xmodel.csv>
                                                      post-link: lodCount == 1
"""
import argparse
import csv
import hashlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / 'docs/staff_presentation_manifest.json'
TARGETS = {
    'source_data/tod_staff_origins.gdt': ['tod_staff_world'],
    'source_data/tod_staff_pap.gdt': ['tod_staff_ice_body_wm', 'tod_staff_ice_tip_wm', 'tod_staff_ice_pap_tip_wm'],
}


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def block_span(text, name):
    head = re.search(r'"' + re.escape(name) + r'"\s*\(\s*"xmodel\.gdf"\s*\)\s*\{', text)
    if not head:
        raise SystemExit('missing xmodel block: ' + name)
    end = text.index('}', head.end())
    return head.end(), end


def switches(body):
    return {k: v for k, v in re.findall(r'"(autogen[A-Za-z0-9]*)"\s*"([^"]*)"', body) if not k.endswith('Percent')}


def apply():
    changed = []
    for rel, names in TARGETS.items():
        path = ROOT / rel
        text = path.read_bytes().decode('latin1')
        for name in names:
            a, b = block_span(text, name)
            body = text[a:b]
            new = re.sub(r'("autogen(?![A-Za-z0-9]*Percent)[A-Za-z0-9]*"\s*")1(")', r'\g<1>0\2', body)
            if new != body:
                changed.append(name)
            text = text[:a] + new + text[b:]
        path.write_bytes(text.encode('latin1'))
    manifest = json.loads(MANIFEST.read_text())
    manifest['files']['source_data/tod_staff_pap.gdt'] = sha(ROOT / 'source_data/tod_staff_pap.gdt')
    MANIFEST.write_text(json.dumps(manifest, indent=2) + '\n')
    print('staff world LODs: switched off on ' + (', '.join(changed) if changed else 'nothing (already applied)'))
    check()


def check():
    for rel, names in TARGETS.items():
        text = (ROOT / rel).read_bytes().decode('latin1')
        for name in names:
            a, b = block_span(text, name)
            sw = switches(text[a:b])
            assert sw, (name, 'no autogen fields found - the GDT layout changed')
            on = [k for k, v in sw.items() if v != '0']
            assert not on, (name, 'autogen LOD switched on - the thin shaft decimates away at range', on)
            assert '"filename"' in text[a:b], (name, 'block lost its filename')
    manifest = json.loads(MANIFEST.read_text())
    assert manifest['files']['source_data/tod_staff_pap.gdt'] == sha(ROOT / 'source_data/tod_staff_pap.gdt'), \
        'docs/staff_presentation_manifest.json pin is stale - run tools/staff_world_lods.py'
    print('STAFF_WORLD_LODS_OK: tod_staff_world + the three ice world models carry no generated LODs.')


def check_compiled(path):
    with Path(path).open(encoding='utf-8-sig', newline='') as stream:
        rows = {r['name']: r for r in csv.DictReader(stream)}
    for names in TARGETS.values():
        for name in names:
            assert name in rows, (name, 'not in the compiled xmodel ledger')
            assert int(rows[name]['lodCount']) == 1, (name, 'compiled with reduced LODs', rows[name]['lodCount'])
    print('STAFF_WORLD_LODS_COMPILED_OK: all four third-person staff models compiled to one full-detail LOD.')


if __name__ == '__main__':
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--check', action='store_true')
    p.add_argument('--compiled-ledger')
    args = p.parse_args()
    if args.compiled_ledger:
        check()
        check_compiled(args.compiled_ledger)
    elif args.check:
        check()
    else:
        apply()
